### ISSUE TITLE
Live Feed never loads: "Camera not responding"

### ISSUE THREAD

**Issue by jandreaucodes** [seydx/homebridge-camera-ui#297]
**Describe the bug**
The snapshot of the two cameras I added work fine. However, when I tap into them to load the live video, it never loads.

I checked the stream in VLC and it loads almost instantly. I also tested adding the cameras into another smart home app (scrypted.app) and it worked there.

I am using two Foscam outdoor IP cameras via RTSP.

**To Reproduce**
Add cameras
View snapshots.
Try to load live video.
Live video fails.

**Expected behavior**
Live video loads.

**Logs**
[11/30/2021, 8:46:11 AM] [CameraUI] [Plugin] Front Door: Snapshot requested: 1280 x 720
[11/30/2021, 8:46:11 AM] [CameraUI] [Plugin] Front Door: Snapshot command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://Mike:Caputo01!!@192.168.5.10:88/videoMain -frames:v 1 -f image2 - -hide_banner -loglevel error
[11/30/2021, 8:46:11 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7fa32f008200] Missing reference picture, default is 65548
[11/30/2021, 8:46:11 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7fa32f008200] Missing reference picture, default is 65550
[11/30/2021, 8:46:11 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7fa32f008200] Missing reference picture, default is 65552
[11/30/2021, 8:46:13 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7fa33100a600] Missing reference picture, default is 65548
[11/30/2021, 8:46:13 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7fa33100ac00] Missing reference picture, default is 65550
[11/30/2021, 8:46:13 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7fa33100b200] Missing reference picture, default is 65552
[11/30/2021, 8:46:13 AM] [CameraUI] [Plugin] Front Door: Fetching snapshot took 2.41 seconds.
[11/30/2021, 8:46:13 AM] [CameraUI] [Plugin] Front Door: Sending snapshot: 1280x720
[11/30/2021, 8:46:13 AM] [CameraUI] [Plugin] Front Door: Resize command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
[11/30/2021, 8:46:13 AM] [CameraUI] [Plugin] Driveway: Snapshot requested: 1280 x 720
[11/30/2021, 8:46:13 AM] [CameraUI] [Plugin] Driveway: Snapshot command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://Mike:Caputo01!!@192.168.4.86:88/videoMain -frames:v 1 -f image2 - -hide_banner -loglevel error
[11/30/2021, 8:46:15 AM] [CameraUI] [Plugin] Driveway: Fetching snapshot took 2.183 seconds.
[11/30/2021, 8:46:15 AM] [CameraUI] [Plugin] Driveway: Sending snapshot: 1280x720
[11/30/2021, 8:46:15 AM] [CameraUI] [Plugin] Driveway: Resize command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
[11/30/2021, 8:46:15 AM] [CameraUI] [Sessions] Driveway added to active sessions
[11/30/2021, 8:46:15 AM] [CameraUI] [Sessions] Currently active streams: {"Driveway":{"activeStreams":1,"maxStreams":5},"Front Door":{"activeStreams":0,"maxStreams":3}}
[11/30/2021, 8:46:15 AM] [CameraUI] [Plugin] Driveway: Video stream requested: 1280x720, 30 fps, 299 kbps
[11/30/2021, 8:46:15 AM] [CameraUI] [Plugin] Driveway: Starting video stream: nativexnative, native fps, 299 kbps
[11/30/2021, 8:46:15 AM] [CameraUI] [Plugin] Driveway: Stream command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://Mike:Caputo01!!@192.168.4.86:88/videoMain -an -sn -dn -codec:v libx264 -pix_fmt yuv420p -color_range mpeg -f rawvideo -preset ultrafast -tune zerolatency -b:v 299k -payload_type 99 -ssrc 16425860 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params CxWy7Y4d0KR3u9i/rTtUmzda/4cC/DksqJdrL2+Z srtp://192.168.4.37:58713?rtcpport=58713&pkt_size=1316 -loglevel level -progress pipe:1
[11/30/2021, 8:46:18 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f9012000] [error] left block unavailable for requested intra mode
[11/30/2021, 8:46:18 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f9012000] [error] error while decoding MB 0 4, bytestream 137512
[11/30/2021, 8:46:18 AM] [CameraUI] [Plugin] Driveway: Getting the first frames took 2.909 seconds.
[11/30/2021, 8:46:20 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f9014a00] [error] cabac decode of qscale diff failed at 85 3
[11/30/2021, 8:46:20 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f9014a00] [error] error while decoding MB 85 3, bytestream 123325
[11/30/2021, 8:46:21 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f9012600] [error] cabac decode of qscale diff failed at 93 7
[11/30/2021, 8:46:21 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f9012600] [error] error while decoding MB 93 7, bytestream 105115
[11/30/2021, 8:46:22 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f900e200] [error] left block unavailable for requested intra mode
[11/30/2021, 8:46:22 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f900e200] [error] error while decoding MB 0 5, bytestream 149879
[11/30/2021, 8:46:22 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f9014400] [error] top block unavailable for requested intra mode -1
[11/30/2021, 8:46:22 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f9014400] [error] error while decoding MB 109 0, bytestream 158001
[11/30/2021, 8:46:24 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f9012000] [error] left block unavailable for requested intra4x4 mode -1
[11/30/2021, 8:46:24 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f9012000] [error] error while decoding MB 0 13, bytestream 116680
[11/30/2021, 8:46:24 AM] [CameraUI] [Plugin] Driveway: Received request to reconfigure: 640x360, 30 fps, 132 kbps (Ignored)
[11/30/2021, 8:46:34 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f9012c00] [error] left block unavailable for requested intra mode
[11/30/2021, 8:46:34 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f9012c00] [error] error while decoding MB 0 21, bytestream 74873
[11/30/2021, 8:46:36 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f7815400] [error] error while decoding MB 66 65, bytestream -7
[11/30/2021, 8:46:42 AM] [CameraUI] [Plugin] Front Door: Snapshot requested: 1280 x 720
[11/30/2021, 8:46:42 AM] [CameraUI] [Plugin] Front Door: Snapshot command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://Mike:Caputo01!!@192.168.5.10:88/videoMain -frames:v 1 -f image2 - -hide_banner -loglevel error
[11/30/2021, 8:46:43 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f9011a00] [error] left block unavailable for requested intra mode
[11/30/2021, 8:46:43 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f9011a00] [error] error while decoding MB 0 29, bytestream 46337
[11/30/2021, 8:46:44 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f7815400] [error] left block unavailable for requested intra mode
[11/30/2021, 8:46:44 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fb9f7815400] [error] error while decoding MB 0 6, bytestream 130156
[11/30/2021, 8:46:44 AM] [CameraUI] [Plugin] Front Door: Fetching snapshot took 2.164 seconds.
[11/30/2021, 8:46:44 AM] [CameraUI] [Plugin] Front Door: Sending snapshot: 1280x720
[11/30/2021, 8:46:44 AM] [CameraUI] [Plugin] Front Door: Resize command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
[11/30/2021, 8:46:44 AM] [CameraUI] [Plugin] Driveway: Snapshot requested: 1280 x 720
[11/30/2021, 8:46:44 AM] [CameraUI] [Plugin] Driveway: Snapshot command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://Mike:Caputo01!!@192.168.4.86:88/videoMain -frames:v 1 -f image2 - -hide_banner -loglevel error
[11/30/2021, 8:46:44 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fdf98008e00] Missing reference picture, default is 65548
[11/30/2021, 8:46:45 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fdf98008e00] Missing reference picture, default is 65550
[11/30/2021, 8:46:45 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fdf98008e00] Missing reference picture, default is 65552
[11/30/2021, 8:46:46 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fdf96012a00] Missing reference picture, default is 65548
[11/30/2021, 8:46:46 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fdf96013000] Missing reference picture, default is 65550
[11/30/2021, 8:46:46 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fdf9601a400] Missing reference picture, default is 65552
[11/30/2021, 8:46:47 AM] [CameraUI] [Plugin] Driveway: Fetching snapshot took 2.579 seconds.
[11/30/2021, 8:46:47 AM] [CameraUI] [Plugin] Driveway: Sending snapshot: 1280x720
[11/30/2021, 8:46:47 AM] [CameraUI] [Plugin] Driveway: Resize command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
[11/30/2021, 8:46:47 AM] [CameraUI] [Sessions] Driveway removed from active sessions
[11/30/2021, 8:46:47 AM] [CameraUI] [Sessions] Currently active streams: {"Driveway":{"activeStreams":0,"maxStreams":5},"Front Door":{"activeStreams":0,"maxStreams":3}}
[11/30/2021, 8:46:47 AM] [CameraUI] [Plugin] Driveway: Stopped video stream.
[11/30/2021, 8:46:47 AM] [CameraUI] [Plugin] Driveway: ffmpeg exited with code: null and signal: SIGKILL (Expected)
[11/30/2021, 8:46:47 AM] [CameraUI] [Sessions] Driveway added to active sessions
[11/30/2021, 8:46:47 AM] [CameraUI] [Sessions] Currently active streams: {"Driveway":{"activeStreams":1,"maxStreams":5},"Front Door":{"activeStreams":0,"maxStreams":3}}
[11/30/2021, 8:46:47 AM] [CameraUI] [Plugin] Driveway: Video stream requested: 1280x720, 30 fps, 299 kbps
[11/30/2021, 8:46:47 AM] [CameraUI] [Plugin] Driveway: Starting video stream: nativexnative, native fps, 299 kbps
[11/30/2021, 8:46:47 AM] [CameraUI] [Plugin] Driveway: Stream command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://Mike:Caputo01!!@192.168.4.86:88/videoMain -an -sn -dn -codec:v libx264 -pix_fmt yuv420p -color_range mpeg -f rawvideo -preset ultrafast -tune zerolatency -b:v 299k -payload_type 99 -ssrc 49368 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params kG6ZSiKdUXsIO/cqKnkMnFbHb6xH9+WqHnedxRbA srtp://192.168.4.37:63199?rtcpport=63199&pkt_size=1316 -loglevel level -progress pipe:1
[11/30/2021, 8:46:47 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf6008e00] [error] Missing reference picture, default is 65546
[11/30/2021, 8:46:47 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf6008e00] [error] Missing reference picture, default is 65548
[11/30/2021, 8:46:47 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf6008e00] [error] Missing reference picture, default is 65550
[11/30/2021, 8:46:47 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf6008e00] [error] Missing reference picture, default is 65552
[11/30/2021, 8:46:49 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf400fc00] [error] Missing reference picture, default is 65546
[11/30/2021, 8:46:49 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf4012e00] [error] Missing reference picture, default is 65548
[11/30/2021, 8:46:49 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf4013400] [error] Missing reference picture, default is 65550
[11/30/2021, 8:46:49 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf4013a00] [error] Missing reference picture, default is 65552
[11/30/2021, 8:46:50 AM] [CameraUI] [Plugin] Driveway: Getting the first frames took 2.967 seconds.
[11/30/2021, 8:46:51 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf4014600] [error] left block unavailable for requested intra4x4 mode -1
[11/30/2021, 8:46:51 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf4014600] [error] error while decoding MB 0 4, bytestream 138174
[11/30/2021, 8:46:52 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf4013400] [error] left block unavailable for requested intra mode
[11/30/2021, 8:46:52 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf4013400] [error] error while decoding MB 0 4, bytestream 128059
[11/30/2021, 8:46:53 AM] [CameraUI] [Plugin] Driveway: Received request to reconfigure: 640x360, 30 fps, 132 kbps (Ignored)
[11/30/2021, 8:46:57 AM] [CameraUI] [Plugin] Front Door: Snapshot requested: 1280 x 720
[11/30/2021, 8:46:57 AM] [CameraUI] [Plugin] Front Door: Snapshot command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://Mike:Caputo01!!@192.168.5.10:88/videoMain -frames:v 1 -f image2 - -hide_banner -loglevel error
[11/30/2021, 8:46:57 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7f95be809200] Missing reference picture, default is 65548
[11/30/2021, 8:46:57 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7f95be809200] Missing reference picture, default is 65550
[11/30/2021, 8:46:57 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7f95be809200] Missing reference picture, default is 65552
[11/30/2021, 8:46:58 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf400f600] [error] left block unavailable for requested intra4x4 mode -1
[11/30/2021, 8:46:58 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf400f600] [error] error while decoding MB 0 2, bytestream 140353
[11/30/2021, 8:46:59 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7f959f813400] Missing reference picture, default is 65548
[11/30/2021, 8:46:59 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7f959f813a00] Missing reference picture, default is 65550
[11/30/2021, 8:46:59 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7f959f81ce00] Missing reference picture, default is 65552
[11/30/2021, 8:46:59 AM] [CameraUI] [Plugin] Front Door: Fetching snapshot took 2.708 seconds.
[11/30/2021, 8:46:59 AM] [CameraUI] [Plugin] Front Door: Sending snapshot: 1280x720
[11/30/2021, 8:46:59 AM] [CameraUI] [Plugin] Front Door: Resize command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
[11/30/2021, 8:47:00 AM] [CameraUI] [Plugin] Driveway: Snapshot requested: 1280 x 720
[11/30/2021, 8:47:00 AM] [CameraUI] [Plugin] Driveway: Snapshot command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://Mike:Caputo01!!@192.168.4.86:88/videoMain -frames:v 1 -f image2 - -hide_banner -loglevel error
[11/30/2021, 8:47:01 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf400fc00] [error] top block unavailable for requested intra mode -1
[11/30/2021, 8:47:01 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf400fc00] [error] error while decoding MB 49 0, bytestream 134588
[11/30/2021, 8:47:04 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf4012e00] [error] left block unavailable for requested intra mode
[11/30/2021, 8:47:04 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf4012e00] [error] error while decoding MB 0 3, bytestream 139041
[Driveway] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
[11/30/2021, 8:47:11 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf4013a00] [error] cabac decode of qscale diff failed at 74 1
[11/30/2021, 8:47:11 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf4013a00] [error] error while decoding MB 74 1, bytestream 133298
[11/30/2021, 8:47:12 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf4014000] [error] left block unavailable for requested intra4x4 mode -1
[11/30/2021, 8:47:12 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf4014000] [error] error while decoding MB 0 13, bytestream 89417
[11/30/2021, 8:47:13 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fe1c7808800] Missing reference picture, default is 65542
[11/30/2021, 8:47:13 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fe1c7808800] Missing reference picture, default is 65544
[11/30/2021, 8:47:13 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fe1c7808800] Missing reference picture, default is 65546
[11/30/2021, 8:47:13 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fe1c7808800] Missing reference picture, default is 65548
[11/30/2021, 8:47:13 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fe1c7808800] Missing reference picture, default is 65550
[11/30/2021, 8:47:13 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fe1c7808800] Missing reference picture, default is 65552
[11/30/2021, 8:47:17 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf4012e00] [error] left block unavailable for requested intra4x4 mode -1
[11/30/2021, 8:47:17 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fdbf4012e00] [error] error while decoding MB 0 11, bytestream 122244
[11/30/2021, 8:47:21 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fe1c780a000] Missing reference picture, default is 65542
[11/30/2021, 8:47:21 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fe1c780a600] Missing reference picture, default is 65544
[11/30/2021, 8:47:21 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fe1c780ac00] Missing reference picture, default is 65546
[11/30/2021, 8:47:21 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fe1c780b200] Missing reference picture, default is 65548
[11/30/2021, 8:47:21 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fe1c780de00] Missing reference picture, default is 65550
[11/30/2021, 8:47:21 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fe196008800] Missing reference picture, default is 65552
[11/30/2021, 8:47:21 AM] [CameraUI] [Plugin] Driveway: Fetching snapshot took 21.47 seconds. It is highly recommended you switch to unbridge mode.
[11/30/2021, 8:47:21 AM] [CameraUI] [Plugin] Driveway: Sending snapshot: 1280x720
[11/30/2021, 8:47:21 AM] [CameraUI] [Plugin] Driveway: Resize command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
[11/30/2021, 8:47:21 AM] [CameraUI] [Sessions] Driveway removed from active sessions
[11/30/2021, 8:47:21 AM] [CameraUI] [Sessions] Currently active streams: {"Driveway":{"activeStreams":0,"maxStreams":5},"Front Door":{"activeStreams":0,"maxStreams":3}}
[11/30/2021, 8:47:21 AM] [CameraUI] [Plugin] Driveway: Stopped video stream.
[11/30/2021, 8:47:21 AM] [CameraUI] [Plugin] Driveway: ffmpeg exited with code: null and signal: SIGKILL (Expected)
[11/30/2021, 8:47:21 AM] [CameraUI] [Plugin] Front Door: Snapshot requested: 1280 x 720
[11/30/2021, 8:47:21 AM] [CameraUI] [Plugin] Front Door: Snapshot command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://Mike:Caputo01!!@192.168.5.10:88/videoMain -frames:v 1 -f image2 - -hide_banner -loglevel error
[11/30/2021, 8:47:23 AM] [CameraUI] [Plugin] Front Door: Fetching snapshot took 2.1 seconds.
[11/30/2021, 8:47:23 AM] [CameraUI] [Plugin] Front Door: Sending snapshot: 1280x720
[11/30/2021, 8:47:23 AM] [CameraUI] [Plugin] Front Door: Resize command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
[11/30/2021, 8:47:23 AM] [CameraUI] [Sessions] Front Door added to active sessions
[11/30/2021, 8:47:23 AM] [CameraUI] [Sessions] Currently active streams: {"Driveway":{"activeStreams":0,"maxStreams":5},"Front Door":{"activeStreams":1,"maxStreams":3}}
[11/30/2021, 8:47:23 AM] [CameraUI] [Plugin] Front Door: Video stream requested: 1280x720, 30 fps, 299 kbps
[11/30/2021, 8:47:23 AM] [CameraUI] [Plugin] Front Door: Starting video stream: 1280x720, 30 fps, 299 kbps
[11/30/2021, 8:47:23 AM] [CameraUI] [Plugin] Front Door: Stream command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://Mike:Caputo01!!@192.168.5.10:88/videoMain -an -sn -dn -codec:v libx264 -pix_fmt yuv420p -color_range mpeg -r 30 -f rawvideo -preset ultrafast -tune zerolatency -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -b:v 299k -payload_type 99 -ssrc 11619216 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params k+PizZnYelKCBKgEhgj3BUfnYPrUbdLhJhmLCfn0 srtp://192.168.4.37:57537?rtcpport=57537&pkt_size=1316 -loglevel level -progress pipe:1
[11/30/2021, 8:47:24 AM] [CameraUI] [Plugin] Front Door: [h264 @ 0x7fd91b008e00] [error] Missing reference picture, default is 65546
[11/30/2021, 8:47:24 AM] [CameraUI] [Plugin] Front Door: [h264 @ 0x7fd91b008e00] [error] Missing reference picture, default is 65548
[11/30/2021, 8:47:24 AM] [CameraUI] [Plugin] Front Door: [h264 @ 0x7fd91b008e00] [error] Missing reference picture, default is 65550
[11/30/2021, 8:47:24 AM] [CameraUI] [Plugin] Front Door: [h264 @ 0x7fd91b008e00] [error] Missing reference picture, default is 65552
[11/30/2021, 8:47:24 AM] [CameraUI] [Sessions] Front Door removed from active sessions
[11/30/2021, 8:47:24 AM] [CameraUI] [Sessions] Currently active streams: {"Driveway":{"activeStreams":0,"maxStreams":5},"Front Door":{"activeStreams":0,"maxStreams":3}}
[11/30/2021, 8:47:24 AM] [CameraUI] [Plugin] Front Door: Stopped video stream.
[11/30/2021, 8:47:24 AM] [CameraUI] [Plugin] Front Door: ffmpeg exited with code: null and signal: SIGKILL (Expected)
[11/30/2021, 8:47:33 AM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /cameras
[11/30/2021, 8:47:34 AM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /stopStream
[11/30/2021, 8:47:34 AM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /stopStream
[11/30/2021, 8:47:37 AM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /startStream
[11/30/2021, 8:47:37 AM] [Homebridge UI] [homebridge-camera-ui] Stream command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://Mike:Caputo01!!@192.168.4.86:88/videoMain -f mpegts -codec:v mpeg1video -s 1280x720 -b:v 299k -r 20 -bf 0 -preset:v ultrafast -threads 1 -codec:a mp2 -ar 44100 -ac 1 -b:a 128k -
[11/30/2021, 8:47:42 AM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /stopStream
[11/30/2021, 8:47:42 AM] [Homebridge UI] [homebridge-camera-ui] Driveway: Stopping stream..
[11/30/2021, 8:47:42 AM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /stopStream
[11/30/2021, 8:48:47 AM] [CameraUI] [Sessions] Driveway added to active sessions
[11/30/2021, 8:48:47 AM] [CameraUI] [Sessions] Currently active streams: {"Driveway":{"activeStreams":1,"maxStreams":5},"Front Door":{"activeStreams":0,"maxStreams":3}}
[11/30/2021, 8:48:47 AM] [CameraUI] [Plugin] Driveway: Video stream requested: 1280x720, 30 fps, 299 kbps
[11/30/2021, 8:48:47 AM] [CameraUI] [Plugin] Driveway: Starting video stream: nativexnative, native fps, 299 kbps
[11/30/2021, 8:48:47 AM] [CameraUI] [Plugin] Driveway: Stream command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://Mike:Caputo01!!@192.168.4.86:88/videoMain -an -sn -dn -codec:v libx264 -pix_fmt yuv420p -color_range mpeg -f rawvideo -preset ultrafast -tune zerolatency -b:v 299k -payload_type 99 -ssrc 11367228 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params GFX4HUkH6KnU2iO6dWTk0GKpy4cEzv6XaRxhSypo srtp://192.168.4.37:50334?rtcpport=50334&pkt_size=1316 -loglevel level -progress pipe:1
[11/30/2021, 8:48:47 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fd24a808e00] [error] Missing reference picture, default is 65548
[11/30/2021, 8:48:47 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fd24a808e00] [error] Missing reference picture, default is 65550
[11/30/2021, 8:48:48 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fd24a808e00] [error] Missing reference picture, default is 65552
[11/30/2021, 8:48:48 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fd24a808e00] [error] left block unavailable for requested intra mode
[11/30/2021, 8:48:48 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fd24a808e00] [error] error while decoding MB 0 51, bytestream 5642
[11/30/2021, 8:48:48 AM] [CameraUI] [Plugin] Front Door: Snapshot requested: 640 x 360
[11/30/2021, 8:48:48 AM] [CameraUI] [Plugin] Front Door: Snapshot command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://Mike:Caputo01!!@192.168.5.10:88/videoMain -frames:v 1 -f image2 - -hide_banner -loglevel error
[11/30/2021, 8:48:49 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7fd6e9008e00] Missing reference picture, default is 65548
[11/30/2021, 8:48:49 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7fd6e9008e00] Missing reference picture, default is 65550
[11/30/2021, 8:48:49 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7fd6e9008e00] Missing reference picture, default is 65552
[11/30/2021, 8:48:49 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fd229027200] [error] Missing reference picture, default is 65548
[11/30/2021, 8:48:49 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fd229027800] [error] Missing reference picture, default is 65550
[11/30/2021, 8:48:49 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fd229008c00] [error] Missing reference picture, default is 65552
[11/30/2021, 8:48:49 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fd229009200] [error] left block unavailable for requested intra mode
[11/30/2021, 8:48:49 AM] [CameraUI] [Plugin] Driveway: [h264 @ 0x7fd229009200] [error] error while decoding MB 0 51, bytestream 5642
[11/30/2021, 8:48:50 AM] [CameraUI] [Sessions] Driveway removed from active sessions
[11/30/2021, 8:48:50 AM] [CameraUI] [Sessions] Currently active streams: {"Driveway":{"activeStreams":0,"maxStreams":5},"Front Door":{"activeStreams":0,"maxStreams":3}}
[11/30/2021, 8:48:50 AM] [CameraUI] [Plugin] Driveway: Stopped video stream.
[11/30/2021, 8:48:50 AM] [CameraUI] [Plugin] Driveway: ffmpeg exited with code: null and signal: SIGKILL (Expected)
[11/30/2021, 8:48:51 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7fd6e601aa00] Missing reference picture, default is 65548
[11/30/2021, 8:48:51 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7fd6e601dc00] Missing reference picture, default is 65550
[11/30/2021, 8:48:51 AM] [CameraUI] [Plugin] Front Door] [Snapshot: [h264 @ 0x7fd6e601e200] Missing reference picture, default is 65552
[11/30/2021, 8:48:51 AM] [CameraUI] [Plugin] Front Door: Fetching snapshot took 2.404 seconds.
[11/30/2021, 8:48:51 AM] [CameraUI] [Plugin] Front Door: Sending snapshot: 640x360
[11/30/2021, 8:48:51 AM] [CameraUI] [Plugin] Front Door: Resize command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(640,iw)':'min(360,ih)':force_original_aspect_ratio=decrease -f image2 -
[11/30/2021, 8:48:51 AM] [CameraUI] [Plugin] Driveway: Snapshot requested: 640 x 360
[11/30/2021, 8:48:51 AM] [CameraUI] [Plugin] Driveway: Snapshot command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://Mike:Caputo01!!@192.168.4.86:88/videoMain -frames:v 1 -f image2 - -hide_banner -loglevel error
[11/30/2021, 8:48:51 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fcaae013800] Missing reference picture, default is 65550
[11/30/2021, 8:48:51 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fcaae013800] Missing reference picture, default is 65552
[11/30/2021, 8:48:53 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fca6e812c00] Missing reference picture, default is 65550
[11/30/2021, 8:48:53 AM] [CameraUI] [Plugin] Driveway] [Snapshot: [h264 @ 0x7fca6e815e00] Missing reference picture, default is 65552
[11/30/2021, 8:48:53 AM] [Homebridge UI] [homebridge-camera-ui] Terminating child process...
[11/30/2021, 8:48:53 AM] [Homebridge UI] [homebridge-camera-ui] Child process ended
[11/30/2021, 8:48:53 AM] [CameraUI] [Plugin] Driveway: Fetching snapshot took 2.291 seconds.
[11/30/2021, 8:48:53 AM] [CameraUI] [Plugin] Driveway: Sending snapshot: 640x360
[11/30/2021, 8:48:53 AM] [CameraUI] [Plugin] Driveway: Resize command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(640,iw)':'min(360,ih)':force_original_aspect_ratio=decrease -f image2 -
**Screenshots**

**Environment**
- Node.js Version: v16.13.0
- Homebridge Version: v4.41.3
- Camera UI Version: v4.2.10
- Operating System: macOS 12.0.1
- Browser: all

**Comment by seydx** [comment]
Hey sry for the late reply, was busy with v5 of camera.ui

can you try version 5 (beta) to check if the issue still exist?

``sudo npm i -g homebridge-camera-ui@beta``

**Comment by beamwerks** [comment]
great project.  just sent you a donation.

i'm having this same/similar issue and upgraded to 5.0.0 beta 20 as you suggested above.  after doing that, the stream inside of camera-ui/homebridge no longer works and i get an ssl protocol error trying to open the camera-ui url

my config with 2 hacked yi cams

{
    "name": "CameraUI",
    "port": 8283,
    "atHomeSwitch": true,
    "debug": false,
    "mqtt": {
        "active": false
    },
    "http": {
        "active": false,
        "localhttp": false
    },
    "smtp": {
        "active": false
    },
    "ssl": {
        "active": false
    },
    "cameras": [
        {
            "name": "Camera_UI_1",
            "unbridge": true,
            "videoConfig": {
                "source": "-rtsp_transport tcp -i rtsp://x.x.x.x/ch0_0.h264",
                "stillImageSource": "-i http://x.x.x.x:8080/cgi-bin/snapshot.sh?res=high&watermark=yes",
                "maxStreams": 4,
                "maxWidth": 1920,
                "maxHeight": 1080,
                "maxFPS": 25,
                "maxBitrate": 1000,
                "audio": false
            }
        },
        {
            "name": "Camera_UI_2",
            "unbridge": true,
            "videoConfig": {
                "source": "-rtsp_transport tcp -i rtsp://x.x.x.x/ch0_0.h264",
                "stillImageSource": "-i http://x.x.x.x:8080/cgi-bin/snapshot.sh?res=high&watermark=yes",
                "maxStreams": 4,
                "maxWidth": 1920,
                "maxHeight": 1080,
                "maxFPS": 25,
                "maxBitrate": 1000,
                "audio": false
            }
        }
    ],
    "platform": "CameraUI"
}


relevant logs
[12/18/2021, 8:22:59 AM] [CameraUI] Camera_UI_1: Configuring unbridged accessory...
[12/18/2021, 8:22:59 AM] [CameraUI] Camera_UI_1: Setting up accessory...
[12/18/2021, 8:22:59 AM] [CameraUI] Camera_UI_2: Configuring unbridged accessory...
[12/18/2021, 8:22:59 AM] [CameraUI] Camera_UI_2: Setting up accessory...
[12/18/2021, 8:22:59 AM] [CameraUI] camera.ui v5.0.0-beta.20 is listening on port 8283 (http)
[12/18/2021, 8:22:59 AM] Camera_UI_1 5CB0 is running on port 52100.
[12/18/2021, 8:22:59 AM] Please add [Camera_UI_1 5CB0] manually in Home app. Setup Code: 031-45-154
[12/18/2021, 8:22:59 AM] Camera_UI_2 B528 is running on port 52101.
[12/18/2021, 8:22:59 AM] Please add [Camera_UI_2 B528] manually in Home app. Setup Code: 031-45-154
[12/18/2021, 8:23:09 AM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /cameras
[12/18/2021, 8:23:10 AM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /stopStream
[12/18/2021, 8:23:10 AM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /stopStream
[12/18/2021, 8:23:12 AM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /startStream
[12/18/2021, 8:23:12 AM] [Homebridge UI] [homebridge-camera-ui] Stream command: /homebridge/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -rtsp_transport tcp -i rtsp://192.168.1.249/ch0_0.h264 -f mpegts -codec:v mpeg1video -s 1920x1080 -b:v 299k -r 25 -bf 0 -preset:v ultrafast -threads 1 -an -q 1 -hide_banner -loglevel error -max_muxing_queue_size 1024 -
[12/18/2021, 8:23:25 AM] [Homebridge UI] [homebridge-camera-ui] Terminating child process...
[12/18/2021, 8:23:25 AM] [Homebridge UI] [homebridge-camera-ui] Child process ended
[12/18/2021, 8:24:49 AM] [CameraUI] Camera_UI_1: Starting video stream: 1920x1080, 25 fps, 802 kbps
[Camera_UI_2 B528] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
[12/18/2021, 8:24:52 AM] [CameraUI] Camera_UI_1: [h264 @ 0x558b3f70e3c0] [error] error while decoding MB 111 49, bytestream -18
[12/18/2021, 8:24:53 AM] [CameraUI] Camera_UI_1: [h264 @ 0x558b3f820f00] [error] error while decoding MB 111 49, bytestream -18
[12/18/2021, 8:24:56 AM] [CameraUI] Camera_UI_1: [h264 @ 0x558b3f8b0e00] [error] error while decoding MB 31 58, bytestream -6
[12/18/2021, 8:25:00 AM] [CameraUI] Camera_UI_1: [h264 @ 0x558b3f8b0e00] [error] error while decoding MB 45 58, bytestream -14
[12/18/2021, 8:25:02 AM] [CameraUI] Camera_UI_1: [h264 @ 0x558b3f8b0e00] [error] cabac decode of qscale diff failed at 49 67
[12/18/2021, 8:25:02 AM] [CameraUI] Camera_UI_1: [h264 @ 0x558b3f8b0e00] [error] error while decoding MB 49 67, bytestream -6
[12/18/2021, 8:25:03 AM] [CameraUI] Camera_UI_2: Fetching snapshot took 18.557 seconds.
[12/18/2021, 8:25:04 AM] [CameraUI] Camera_UI_1: [h264 @ 0x558b3f836140] [error] cabac decode of qscale diff failed at 93 47
[12/18/2021, 8:25:04 AM] [CameraUI] Camera_UI_1: [h264 @ 0x558b3f836140] [error] error while decoding MB 93 47, bytestream -4
[12/18/2021, 8:25:04 AM] [CameraUI] Camera_UI_1: Stopped video stream.

**Comment by seydx** [comment]
Hey can u update to the latest beta pls

**Comment by beamwerks** [comment]
no luck.  think these are all the relevant logs.  just spins in homekit.  looks like it's working fine in the homebridge camera ui panel but also still get the ssl protocol error loading the camera ui webpage


[12/22/2021, 10:42:40 PM] [CameraUI] Camera_UI_1: Setting up camera, please be patient...
[12/22/2021, 10:42:40 PM] [CameraUI] Camera_UI_1: Probe stream: -i rtsp://x.x.x.x/ch0_0.h264
[12/22/2021, 10:42:43 PM] [CameraUI] Camera_UI_1: {"probe":true,"timedout":false,"audio":[],"video":["h264 (Main)","yuvj420p(pc","bt709","progressive)","1920x1080","20 fps","20 tbr","90k tbn","40 tbc"]}
[12/22/2021, 10:42:49 PM] [CameraUI] Camera_UI_1: Configuring unbridged accessory...
[12/22/2021, 10:42:49 PM] [CameraUI] Camera_UI_1: Setting up accessory...
[12/22/2021, 10:44:22 PM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /cameras
[12/22/2021, 10:44:23 PM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /stopStream
[12/22/2021, 10:44:23 PM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /stopStream
[12/22/2021, 10:44:23 PM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /stopStream
Incoming Request: /stopStream
[12/22/2021, 10:44:23 PM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /stopStream
[12/22/2021, 10:44:23 PM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /stopStream
[12/22/2021, 10:44:34 PM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /startStream
[12/22/2021, 10:44:34 PM] [Homebridge UI] [homebridge-camera-ui] Stream command: /homebridge/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -rtsp_transport tcp -i rtsp://x.x.x.x/ch0_0.h264 -f mpegts -codec:v mpeg1video -s 1920x1080 -b:v 299k -r 25 -bf 0 -preset:v ultrafast -threads 1 -an -q 1 -hide_banner -loglevel error -max_muxing_queue_size 1024 -
[12/22/2021, 10:44:42 PM] [Homebridge UI] [homebridge-camera-ui] Incoming Request: /stopStream
[12/22/2021, 10:44:42 PM] [Homebridge UI] [homebridge-camera-ui] Camera_UI_1: Stopping stream..
[12/22/2021, 10:44:42 PM] [Homebridge UI] [homebridge-camera-ui] Camera_UI_1: Stream Exit (expected)
[12/22/2021, 10:45:06 PM] [CameraUI] Camera_UI_1: Snapshot requested: 1280 x 720
[12/22/2021, 10:45:06 PM] [CameraUI] Camera_UI_1: Snapshot command: /homebridge/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i http://x.x.x.x:8080/cgi-bin/snapshot.sh?res=high&watermark=yes -frames:v 1 -f image2 - -hide_banner -loglevel error
[12/22/2021, 10:45:12 PM] [CameraUI] Camera_UI_1: Video stream requested: 1280x720, 30 fps, 299 kbps
[12/22/2021, 10:45:12 PM] [CameraUI] Camera_UI_1: Starting video stream: 1280x720, 25 fps, 299 kbps
[12/22/2021, 10:45:12 PM] [CameraUI] Camera_UI_1: Incoming ping request for: rtsp://x.x.x.x/ch0_0.h264 - Timeout: 1s
[12/22/2021, 10:45:12 PM] [CameraUI] Camera_UI_1: Pinging rtsp://x.x.x.x
[12/22/2021, 10:45:12 PM] [CameraUI] Camera_UI_1: Pinging rtsp://x.x.x.x - successful
[12/22/2021, 10:45:12 PM] [CameraUI] Camera_UI_1: Stream command: /homebridge/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -rtsp_transport tcp -i rtsp://x.x.x.x/ch0_0.h264 -an -sn -dn -codec:v libx264 -pix_fmt yuv420p -color_range mpeg -r 25 -f rawvideo -preset ultrafast -tune zerolatency -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -b:v 299k -payload_type 99 -ssrc 14401038 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params ZCK/VLoP0r5MPhaM2WgQ+azXD2+kDsnUVcLhL9v+ srtp://192.168.1.38:56567?rtcpport=56567&pkt_size=1316 -loglevel level -progress pipe:1
[12/22/2021, 10:45:16 PM] [CameraUI] Camera_UI_1: Getting the first frames took 3.733 seconds.
[12/22/2021, 10:45:20 PM] [CameraUI] Camera_UI_1: Snapshot requested: 1280 x 720
[12/22/2021, 10:45:20 PM] [CameraUI] Camera_UI_1: Snapshot command: /homebridge/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i http://x.x.x.x:8080/cgi-bin/snapshot.sh?res=high&watermark=yes -frames:v 1 -f image2 - -hide_banner -loglevel error
[12/22/2021, 10:45:22 PM] [CameraUI] Camera_UI_1: Fetching snapshot took 2.486 seconds.
[12/22/2021, 10:45:22 PM] [CameraUI] Camera_UI_1: Sending snapshot: 1280x720
[12/22/2021, 10:45:22 PM] [CameraUI] Camera_UI_1: Resize command: /homebridge/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
[12/22/2021, 10:45:22 PM] [CameraUI] Camera_UI_1: Stopped video stream.
[12/22/2021, 10:45:22 PM] [CameraUI] Camera_UI_1: ffmpeg exited with code: null and signal: SIGKILL (Expected)

**Comment by seydx** [comment]
Can u post the ssl error pls

**Comment by beamwerks** [comment]
![camerauissl](https://user-images.githubusercontent.com/37078503/147304232-9708bce8-3f67-4322-a772-be9ff3b5676e.png)

**Comment by beamwerks** [comment]
the same page/url works perfect when i downgrade back to the latest non beta version

**Comment by seydx** [comment]
Hm do you open httpS without ssl configured?

Or does your browser auto redirect from http to httpS ?

can u delete your browser cache pls and try again

**Comment by beamwerks** [comment]
it's auto redirecting.  cleared cache, tried chrome incognito, edge and safari.  all the same.  don't worry about it on xmas eve!

**Comment by seydx** [comment]
Ah ok will check it thx

yeah merry christmas 😄

**Comment by seydx** [comment]
> it's auto redirecting. cleared cache, tried chrome incognito, edge and safari. all the same. don't worry about it on xmas eve!

Should be fixed in v5.0.0-beta.26

**Comment by beamwerks** [comment]
beautiful.  and a very well designed page too.

still struggling on getting streaming to work thru the homekit app.   any confirmed working configs for yi hack v5 cameras?   logs look very similar to this https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/710 so doesn't look like any issue with your work

**Comment by seydx** [comment]
Thats my config for a hacked yi dome

```

 {
      "name": "Keller Kamera 2",
      "manufacturer": "Yi",
      "model": "IP Camera",
      "serialNumber": "000000",
      "excludeSwitch": true,
      "privacySwitch": true,
      "motion": true,
      "doorbell": true,
      "switches": true,
      "motionTimeout": 15,
      "motionDoorbell": true,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "videoConfig": {
        "source": "-i rtsp://192.168.178.31/ch0_1.h264",
        "stillImageSource": "-i rtsp://192.168.178.31/ch0_1.h264",
        "readRate": false,
        "rtspTransport": "tcp",
        "maxStreams": 4,
        "maxWidth": 1920,
        "maxHeight": 1080,
        "maxFPS": 20,
        "maxBitrate": 100,
        "forceMax": true,
        "vcodec": "copy",
        "acodec": "copy",
        "stimeout": 10,
        "encoderOptions": "-preset ultrafast -tune zerolatency",
        "audio": false,
        "debug": true
      },
      "mqtt": {
        "motionTopic": "yicam_dome_keller/motion",
        "motionMessage": "ON",
        "motionResetTopic": "yicam_dome_keller/motion",
        "motionResetMessage": "OFF"
      }
    }
```

**Comment by seydx** [comment]
@beamwerks 

can u try v5.0.0-beta.36 pls

``sudo npm i -g homebridge-camera-ui@5.0.0-beta.36``

**Comment by beamwerks** [comment]
sorry been busy on my own project (windfield.app if you have a garmin)

just installed .36 but still not getting homekit to stream even with your recommended settings above.  i briefly got it to work a few nights ago but nothing since despite trying all kinds of different options.  had to put it aside for a bit for now
