### ISSUE TITLE
Skip saving the recording.... HSV not working 5.0.0-beta

### ISSUE THREAD

**Issue by grzegorz914** [seydx/homebridge-camera-ui#317]
Hi,

thanks for the nice plugin but every motion detect I get this in log and the recording to HSV is skipped.
All other functions working correct.
Any tip why this happened?

```
[8.01.2022, 14:09:04] [CameraUI] Przód: Motion ON
[8.01.2022, 14:09:13] [CameraUI] Przód: Closing recording process
[8.01.2022, 14:09:13] [CameraUI] Przód: Skip saving the recording, the file might be corrupted because the recording process was cancelled by HSV
[8.01.2022, 14:09:19] [CameraUI] Przód: Motion handler timeout.
```

HB 1.4.0-beta.4
Node 16.13.1

**Comment by seydx** [comment]
@grzegorz914

It seems that HSV cancelled the recording process because of corrupt data. Can you post your config.json pls

Can you also post a screenshot of the camera's own settings please. Like FPS, bitrate etc

Also a log with enabled debugging would be very helpful

**Comment by grzegorz914** [comment]
```
{
                    "name": "Tył",
                    "manufacturer": "iDom",
                    "model": "iDom",
                    "serialNumber": "987654321",
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://xxxxx:xxxxx@192.168.1.27/1/h264major",
                        "stillImageSource": "-i http://xxxxx:xxxxx@192.168.1.27/jpgmulreq/1/image.jpg?key=1579600903456&lq=1",
                        "rtspTransport": "tcp",
                        "maxStreams": 1,
                        "forceMax": false,
                        "vcodec": "libx264",
                        "acodec": "libfdk_aac",
                        "stimeout": 0
                    },
                    "videoanalysis": {
                        "active": true
                    }
                },
```

**Comment by seydx** [comment]
@grzegorz914 

config.json seems correct, can u enable debug and post the whole log pls

https://github.com/seydx/homebridge-camera-ui/blob/5a19edb2350310a492777dbb7dd05f122858265f/example-config.json#L15

https://github.com/seydx/homebridge-camera-ui/blob/5a19edb2350310a492777dbb7dd05f122858265f/example-config.json#L79

**Comment by grzegorz914** [comment]
```
[8.01.2022, 14:33:09] [CameraUI] Initializing camera.ui with PID: 29029
[8.01.2022, 14:33:10] [CameraUI] Tył: Setting up camera, please be patient...
[8.01.2022, 14:33:10] [CameraUI] Tył: Probe stream: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://xxx:xxx@192.168.1.27/1/h264major
[8.01.2022, 14:33:10] [CameraUI] Przód: Setting up camera, please be patient...
[8.01.2022, 14:33:10] [CameraUI] Przód: Probe stream: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://xxx:xxx@192.168.1.26/1/h264major
[8.01.2022, 14:33:10] [CameraUI] Tył: {"probe":true,"timedout":false,"audio":["adpcm_g726le","8000 Hz","mono","s16","40 kb/s"],"video":["h264 (Main)","yuvj420p(pc","bt470bg/bt470bg/bt709","progressive)","1920x1080","25 tbr","90k tbn","50 tbc"]}
[8.01.2022, 14:33:10] [CameraUI] Tył: Incoming ping request for: rtsp://xxx:xxx@192.168.1.27/1/h264major - Timeout: 1s
[8.01.2022, 14:33:10] [CameraUI] Tył: Pinging 192.168.1.27
[8.01.2022, 14:33:10] [CameraUI] Tył: Pinging 192.168.1.27 - successful
[8.01.2022, 14:33:10] [CameraUI] Tył: Start prebuffering...
[8.01.2022, 14:33:10] [CameraUI] Tył: Prebuffering command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -loglevel error -fflags +genpts -rtsp_transport tcp -i rtsp://xxx:xxx@192.168.1.27/1/h264major -vcodec copy -an -movflags frag_keyframe+empty_moov+default_base_moof -f mp4 tcp://127.0.0.1:39206 -vcodec copy -an -f mpegts tcp://127.0.0.1:26536
[8.01.2022, 14:33:10] [CameraUI] Przód: {"probe":true,"timedout":false,"audio":["adpcm_g726le","8000 Hz","mono","s16","40 kb/s"],"video":["h264 (Main)","yuvj420p(pc","bt470bg/bt470bg/bt709","progressive)","1920x1080","25 tbr","90k tbn","50 tbc"]}
[8.01.2022, 14:33:10] [CameraUI] Przód: Incoming ping request for: rtsp://xxx:xxx@192.168.1.26/1/h264major - Timeout: 1s
[8.01.2022, 14:33:10] [CameraUI] Przód: Pinging 192.168.1.26
[8.01.2022, 14:33:10] [CameraUI] Przód: Pinging 192.168.1.26 - successful
[8.01.2022, 14:33:10] [CameraUI] Przód: Start prebuffering...
[8.01.2022, 14:33:10] [CameraUI] Przód: Prebuffering command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -loglevel error -fflags +genpts -rtsp_transport tcp -i rtsp://xxx:xxx@192.168.1.26/1/h264major -vcodec copy -an -movflags frag_keyframe+empty_moov+default_base_moof -f mp4 tcp://127.0.0.1:32915 -vcodec copy -an -f mpegts tcp://127.0.0.1:11505
[8.01.2022, 14:33:11] [CameraUI] Tył: Prebuffering scheduled for restart at 2AM: 687 minutes
[8.01.2022, 14:33:11] [CameraUI] Tył: Incoming ping request for: rtsp://xxx:xxx@192.168.1.27/1/h264major - Timeout: 1s
[8.01.2022, 14:33:11] [CameraUI] Tył: Pinging 192.168.1.27
[8.01.2022, 14:33:11] [CameraUI] Tył: Pinging 192.168.1.27 - successful
[8.01.2022, 14:33:11] [CameraUI] Tył: Start videoanalysis...
[8.01.2022, 14:33:11] [CameraUI] Tył: Videoanalysis command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -loglevel error -hwaccel auto -analyzeduration 0 -probesize 500000 -f mpegts -i tcp://127.0.0.1:15523 -an -vcodec pam -pix_fmt gray -f image2pipe -vf fps=2,scale=400:225 pipe:1
[8.01.2022, 14:33:11] [CameraUI] Tył: Videoanalysis scheduled for restart at 3AM: 747 minutes
[8.01.2022, 14:33:11] [CameraUI] Przód: Prebuffering scheduled for restart at 2AM: 687 minutes
[8.01.2022, 14:33:11] [CameraUI] Przód: Incoming ping request for: rtsp://xxx:xxx@192.168.1.26/1/h264major - Timeout: 1s
[8.01.2022, 14:33:11] [CameraUI] Przód: Pinging 192.168.1.26
[8.01.2022, 14:33:12] [CameraUI] Przód: Pinging 192.168.1.26 - successful
[8.01.2022, 14:33:12] [CameraUI] Przód: Start videoanalysis...
[8.01.2022, 14:33:12] [CameraUI] Przód: Videoanalysis command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -loglevel error -hwaccel auto -analyzeduration 0 -probesize 500000 -f mpegts -i tcp://127.0.0.1:28898 -an -vcodec pam -pix_fmt gray -f image2pipe -vf fps=2,scale=400:225 pipe:1
[8.01.2022, 14:33:12] [CameraUI] Przód: Videoanalysis scheduled for restart at 3AM: 747 minutes
[8.01.2022, 14:33:12] [CameraUI] Tył: Configuring unbridged accessory...
[8.01.2022, 14:33:12] [CameraUI] Tył: Setting up accessory...
[8.01.2022, 14:33:12] [CameraUI] Tył: Initializing HomeKit Secure Video
[8.01.2022, 14:33:12] [CameraUI] Przód: Configuring unbridged accessory...
[8.01.2022, 14:33:12] [CameraUI] Przód: Setting up accessory...
[8.01.2022, 14:33:12] [CameraUI] Przód: Initializing HomeKit Secure Video
[8.01.2022, 14:33:12] [CameraUI] camera.ui v5.0.0-beta.56 is listening on port 8181 (http)
[8.01.2022, 14:33:15] [CameraUI] admin (::ffff:192.168.0.110) disconnecting from socket, not authenticated
[8.01.2022, 14:33:15] [CameraUI] POST /api/auth/logout 200 7.628 ms - 2
[8.01.2022, 14:33:27] [CameraUI] POST /api/auth/login 201 16.952 ms - 401
[8.01.2022, 14:33:27] [CameraUI] GET /api/config 200 26.111 ms - 211
[8.01.2022, 14:33:28] [CameraUI] GET /api/auth/check 304 3.916 ms - -
[8.01.2022, 14:33:28] [CameraUI] admin (::ffff:192.168.0.110) authenticated and connected to socket
[8.01.2022, 14:33:28] [CameraUI] GET /api/cameras 304 10.211 ms - -
[8.01.2022, 14:33:28] [CameraUI] GET /api/cameras/Ty%C5%82/settings 304 8.868 ms - -
[8.01.2022, 14:33:28] [CameraUI] GET /api/cameras/Prz%C3%B3d/settings 304 9.347 ms - -
[8.01.2022, 14:33:28] [CameraUI] GET /api/settings/widgets 304 11.841 ms - -
[8.01.2022, 14:33:28] [CameraUI] Tył: Incoming ping request for: rtsp://xxx:xxx@192.168.1.27/1/h264major - Timeout: 1s
[8.01.2022, 14:33:28] [CameraUI] Tył: Pinging 192.168.1.27
[8.01.2022, 14:33:28] [CameraUI] Przód: Incoming ping request for: rtsp://xxx:xxx@192.168.1.26/1/h264major - Timeout: 1s
[8.01.2022, 14:33:28] [CameraUI] Przód: Pinging 192.168.1.26
[8.01.2022, 14:33:28] [CameraUI] Przód: Pinging 192.168.1.26 - successful
[8.01.2022, 14:33:28] [CameraUI] GET /api/cameras/Prz%C3%B3d/status?timeout=1 304 77.355 ms - -
[8.01.2022, 14:33:28] [CameraUI] Tył: Pinging 192.168.1.27 - successful
[8.01.2022, 14:33:28] [CameraUI] GET /api/cameras/Ty%C5%82/status?timeout=1 304 92.972 ms - -
[8.01.2022, 14:33:29] [CameraUI] Active sockets in room (stream/Przód): 1
[8.01.2022, 14:33:29] [CameraUI] Przód: New stream added to active sessions
[8.01.2022, 14:33:29] [CameraUI] Przód: Currently active streams: 1
[8.01.2022, 14:33:29] [CameraUI] admin (::ffff:192.168.0.110) joined stream: Przód
[8.01.2022, 14:33:29] [CameraUI] Przód: Setting prebuffer stream as input
[8.01.2022, 14:33:29] [CameraUI] Przód: Stream command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -loglevel error -analyzeduration 0 -probesize 2307136 -f mpegts -i tcp://127.0.0.1:34877 -f mpegts -codec:v mpeg1video -s 1920x1080 -b:v 299k -r 20 -bf 0 -preset:v ultrafast -threads 1 -an -q 1 -max_muxing_queue_size 1024 -
[8.01.2022, 14:33:29] [CameraUI] Active sockets in room (stream/Tył): 1
[8.01.2022, 14:33:29] [CameraUI] Tył: New stream added to active sessions
[8.01.2022, 14:33:29] [CameraUI] Tył: Currently active streams: 1
[8.01.2022, 14:33:29] [CameraUI] admin (::ffff:192.168.0.110) joined stream: Tył
[8.01.2022, 14:33:29] [CameraUI] Tył: Setting prebuffer stream as input
[8.01.2022, 14:33:29] [CameraUI] Tył: Stream command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -loglevel error -analyzeduration 0 -probesize 2315220 -f mpegts -i tcp://127.0.0.1:19275 -f mpegts -codec:v mpeg1video -s 1920x1080 -b:v 299k -r 20 -bf 0 -preset:v ultrafast -threads 1 -an -q 1 -max_muxing_queue_size 1024 -
[8.01.2022, 14:33:31] [CameraUI] GET /api/auth/check 304 2.146 ms - -
[8.01.2022, 14:33:31] [CameraUI] Active sockets in room (stream/Tył): 0
[8.01.2022, 14:33:31] [CameraUI] If no clients connects to the Websocket, the stream will be closed in 15s
[8.01.2022, 14:33:31] [CameraUI] admin (::ffff:192.168.0.110) left stream: Tył
[8.01.2022, 14:33:31] [CameraUI] Active sockets in room (stream/Przód): 0
[8.01.2022, 14:33:31] [CameraUI] If no clients connects to the Websocket, the stream will be closed in 15s
[8.01.2022, 14:33:31] [CameraUI] admin (::ffff:192.168.0.110) left stream: Przód
[8.01.2022, 14:39:24] [CameraUI] Przód: Motion ON
[8.01.2022, 14:39:24] [CameraUI] Przód: Handling event: Motion switched on
[8.01.2022, 14:39:24] [CameraUI] Received a new VIDEOANALYSIS message {"error":false,"message":"Handled through extern controller"} (Przód)
[8.01.2022, 14:39:25] [CameraUI] Przód: Video fragments requested from HSV
[8.01.2022, 14:39:25] [CameraUI] Przód: Setting prebuffer stream as input
[8.01.2022, 14:39:25] [CameraUI] Przód: Prebuffer requested with a duration of -4s
[8.01.2022, 14:39:25] [CameraUI] Przód: Start recording...
[8.01.2022, 14:39:25] [CameraUI] Przód: Recording command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -analyzeduration 0 -probesize 1527650 -f mp4 -i tcp://127.0.0.1:19666 -f mp4 -sn -dn -vcodec libx264 -pix_fmt yuv420p -profile:v baseline -level:v 3.1 -b:v 2000k -force_key_frames expr:eq(t,n_forced*4) -r 30 -vf scale=w=1920:h=1080:force_original_aspect_ratio=1,pad=1920:1080:(ow-iw)/2:(oh-ih)/2 -an -movflags frag_keyframe+empty_moov+default_base_moof -max_muxing_queue_size 1024 tcp://127.0.0.1:22855
[8.01.2022, 14:39:25] [CameraUI] Przód: Recording started
[8.01.2022, 14:39:34] [CameraUI] Przód: Closing recording process
[8.01.2022, 14:39:34] [CameraUI] Resetting motion state because HSV closed recording with reason "3"
[8.01.2022, 14:39:34] [CameraUI] Przód: FFMPEG socket closed during read for 8 bytes!
[8.01.2022, 14:39:34] [CameraUI] Przód: Skip saving the recording, the file might be corrupted because the recording process was cancelled by HSV
[8.01.2022, 14:39:34] [CameraUI] Przód: Prebuffer request ended
[8.01.2022, 14:39:34] [CameraUI] Przód: FFmpeg recording process exited (expected)
```

**Comment by seydx** [comment]
For debugging purposes, can you please also turn on ffmpeg debug on a camera where HSV is not working. Also tried "vcodec": "copy"?

**Comment by grzegorz914** [comment]
looks like with "codec":"copy" working

```
[8.01.2022, 14:56:37] [CameraUI] Przód: Motion ON
[8.01.2022, 14:56:37] [CameraUI] Przód: Handling event: Motion switched on
[8.01.2022, 14:56:37] [CameraUI] Received a new VIDEOANALYSIS message {"error":false,"message":"Handled through extern controller"} (Przód)
[8.01.2022, 14:56:38] [CameraUI] Przód: Video fragments requested from HSV
[8.01.2022, 14:56:38] [CameraUI] Przód: Setting prebuffer stream as input
[8.01.2022, 14:56:38] [CameraUI] Przód: Prebuffer requested with a duration of -4s
[8.01.2022, 14:56:38] [CameraUI] Przód: Start recording...
[8.01.2022, 14:56:38] [CameraUI] Przód: Recording command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -analyzeduration 0 -probesize 1553755 -f mp4 -i tcp://127.0.0.1:23166 -f mp4 -vcodec copy -an -movflags frag_keyframe+empty_moov+default_base_moof -max_muxing_queue_size 1024 tcp://127.0.0.1:32370
[8.01.2022, 14:56:38] [CameraUI] Przód: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'tcp://127.0.0.1:23166':
                                                                                                          Metadata:
                                                                                                                       major_brand     : iso5
                                                                                                                                                 minor_version   : 512
                                                                                                                                                                          compatible_brands: iso5iso6mp41
                                   title           : h264major
                                                                  encoder         : Lavf58.45.100
                                                                                                     comment         : h264major
                                                                                                                                  Duration: 
[8.01.2022, 14:56:38] [CameraUI] Przód: 00:00:26.28, start: 25.280000, bitrate: N/A
                                                                                       Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(pc, bt470bg/bt470bg/bt709), 1920x1080, 111 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc (default)
                                                                              Metadata:
                                                                                             handler_name    : VideoHandler
                                                                                                                           Output #0, mp4, to 'tcp://127.0.0.1:32370':
                                                                                                                                                                        Metadata:
           major_brand     : iso5
                                     minor_version   : 512
                                                              compatible_brands: iso5iso6mp41
                                                                                                 title           : h264major
                                                                                                                                comment         : h264major
                                                                                                                                                               encoder         : Lavf58.45.100
                        Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(pc, bt470bg/bt470bg/bt709), 1920x1080, q=2-31, 111 kb/s, 25 fps, 25 tbr, 90k tbn, 90k tbc (default)
                        Metadata:
                                       handler_name    : VideoHandler
                                                                     Stream mapping:
                                                                                      Stream #0:0 -> #0:0 (copy)
                                                                                                                Press [q] to stop, [?] for help

[8.01.2022, 14:56:38] [CameraUI] Przód: Recording started
[8.01.2022, 14:56:39] [CameraUI] Przód: frame=  127 fps=0.0 q=-1.0 size=    1800kB time=00:00:05.04 bitrate=2925.1kbits/s speed=5.43x    
[8.01.2022, 14:56:40] [CameraUI] Przód: frame=  152 fps= 79 q=-1.0 size=    2120kB time=00:00:06.04 bitrate=2875.2kbits/s speed=3.15x    
[8.01.2022, 14:56:41] [CameraUI] Przód: frame=  177 fps= 60 q=-1.0 size=    2459kB time=00:00:07.04 bitrate=2861.2kbits/s speed= 2.4x    
[8.01.2022, 14:56:42] [CameraUI] Przód: frame=  202 fps= 52 q=-1.0 size=    2766kB time=00:00:08.04 bitrate=2818.0kbits/s speed=2.05x    
[8.01.2022, 14:56:43] [CameraUI] Przód: frame=  227 fps= 46 q=-1.0 size=    3114kB time=00:00:09.04 bitrate=2822.3kbits/s speed=1.83x    
[8.01.2022, 14:56:44] [CameraUI] Przód: frame=  252 fps= 43 q=-1.0 size=    3470kB time=00:00:10.04 bitrate=2831.3kbits/s speed= 1.7x    
[8.01.2022, 14:56:45] [CameraUI] Przód: frame=  277 fps= 40 q=-1.0 size=    3839kB time=00:00:11.04 bitrate=2848.5kbits/s speed=1.59x    
[8.01.2022, 14:56:46] [CameraUI] Przód: frame=  302 fps= 38 q=-1.0 size=    4201kB time=00:00:12.04 bitrate=2858.2kbits/s speed=1.52x    
[8.01.2022, 14:56:47] [CameraUI] Przód: frame=  327 fps= 36 q=-1.0 size=    4550kB time=00:00:13.04 bitrate=2858.5kbits/s speed=1.45x    
[8.01.2022, 14:56:48] [CameraUI] Przód: frame=  352 fps= 35 q=-1.0 size=    4915kB time=00:00:14.04 bitrate=2867.7kbits/s speed=1.42x    
[8.01.2022, 14:56:49] [CameraUI] Przód: frame=  377 fps= 35 q=-1.0 size=    5290kB time=00:00:15.04 bitrate=2881.2kbits/s speed=1.38x    
[8.01.2022, 14:56:50] [CameraUI] Przód: frame=  402 fps= 34 q=-1.0 size=    5669kB time=00:00:16.04 bitrate=2895.1kbits/s speed=1.35x    
[8.01.2022, 14:56:51] [CameraUI] Przód: frame=  427 fps= 33 q=-1.0 size=    6040kB time=00:00:17.04 bitrate=2903.8kbits/s speed=1.32x    
[8.01.2022, 14:56:52] [CameraUI] Przód: frame=  452 fps= 32 q=-1.0 size=    6413kB time=00:00:18.04 bitrate=2912.2kbits/s speed= 1.3x    
[8.01.2022, 14:56:52] [CameraUI] Przód: Motion handler timeout.
[8.01.2022, 14:56:53] [CameraUI] Przód: Ending recording session in 3s
[8.01.2022, 14:56:53] [CameraUI] Przód: frame=  477 fps= 32 q=-1.0 size=    6786kB time=00:00:19.04 bitrate=2919.9kbits/s speed=1.28x    
[8.01.2022, 14:56:54] [CameraUI] Przód: frame=  502 fps= 32 q=-1.0 size=    7160kB time=00:00:20.04 bitrate=2926.7kbits/s speed=1.26x    
[8.01.2022, 14:56:55] [CameraUI] Przód: frame=  527 fps= 31 q=-1.0 size=    7534kB time=00:00:21.04 bitrate=2933.4kbits/s speed=1.24x    
[8.01.2022, 14:56:56] [CameraUI] Przód: frame=  552 fps= 31 q=-1.0 size=    7906kB time=00:00:22.04 bitrate=2938.7kbits/s speed=1.23x    
[8.01.2022, 14:56:57] [CameraUI] Przód: Recording completed (HSV)
[8.01.2022, 14:56:57] [CameraUI] Przód: frame=  577 fps= 30 q=-1.0 size=    8341kB time=00:00:23.04 bitrate=2965.6kbits/s speed=1.22x    
[8.01.2022, 14:56:57] [CameraUI] Przód: New custom alert
[8.01.2022, 14:56:57] [CameraUI] Przód: Notifications not enabled, skip Webhook..
[8.01.2022, 14:56:57] [CameraUI] Przód: Notifications not enabled, skip Alexa..
[8.01.2022, 14:56:57] [CameraUI] Przód: Recording not enabled, skip recording..
[8.01.2022, 14:56:57] [CameraUI] Przód: Notifications not enabled, skip Webpush..
[8.01.2022, 14:56:57] [CameraUI] Przód: Recording skipped. Notification skipped.
[8.01.2022, 14:56:57] [CameraUI] Przód: Closing recording process
[8.01.2022, 14:56:57] [CameraUI] Przód: Prebuffer request ended
[8.01.2022, 14:56:57] [CameraUI] Przód: FFmpeg recording process exited (expected)
```

in other things if use h264_omx get other error:

```
[8.01.2022, 15:03:15] [CameraUI] Przód: [warning] Codec AVOption preset (Set the encoding preset (cf. x264 --fullhelp)) specified for output file #0 (srtp://192.168.1.81:64668?rtcpport=64668&pkt_size=1316) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
[8.01.2022, 15:03:15] [CameraUI] Przód: [info] Stream mapping:
[8.01.2022, 15:03:15] [CameraUI] Przód: [info]   Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_omx))
[8.01.2022, 15:03:15] [CameraUI] Przód: [info] Press [q] to stop, [?] for help
[8.01.2022, 15:03:15] [CameraUI] Przód: [h264 @ 0x4096160] [verbose] Reinit context to 1920x1088, pix_fmt: yuvj420p
[8.01.2022, 15:03:15] [CameraUI] Przód: [Parsed_scale_0 @ 0x4094890] [verbose] w:min(1280,iw) h:min(720,ih) flags:'bicubic' interl:0
[8.01.2022, 15:03:15] [CameraUI] Przód: [Parsed_scale_1 @ 0x4231770] [verbose] w:trunc(iw/2)*2 h:trunc(ih/2)*2 flags:'bicubic' interl:0
[8.01.2022, 15:03:15] [CameraUI] Przód: [graph 0 input from stream 0:0 @ 0x48bd700] [verbose] w:1920 h:1080 pixfmt:yuvj420p tb:1/90000 fr:25/1 sar:0/1
[8.01.2022, 15:03:15] [CameraUI] Przód: [swscaler @ 0x48be320] [warning] deprecated pixel format used, make sure you did set range correctly
[8.01.2022, 15:03:15] [CameraUI] Przód: [Parsed_scale_0 @ 0x4094890] [verbose] w:1920 h:1080 fmt:yuvj420p sar:0/1 -> w:1280 h:720 fmt:yuvj420p sar:0/1 flags:0x4
[8.01.2022, 15:03:15] [CameraUI] Przód: [swscaler @ 0x48fc0a0] [warning] deprecated pixel format used, make sure you did set range correctly
[8.01.2022, 15:03:15] [CameraUI] Przód: [Parsed_scale_1 @ 0x4231770] [verbose] w:1280 h:720 fmt:yuvj420p sar:0/1 -> w:1280 h:720 fmt:yuv420p sar:0/1 flags:0x4
[8.01.2022, 15:03:15] [CameraUI] Przód: [h264_omx @ 0x4095dc0] [warning] /opt/vc/lib/libbcm_host.so not found
[8.01.2022, 15:03:15] [CameraUI] Przód: [error] Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[8.01.2022, 15:03:15] [CameraUI] Przód: [AVIOContext @ 0x40b61c0] [verbose] Statistics: 0 seeks, 0 writeouts
[8.01.2022, 15:03:15] [CameraUI] Przód: [AVIOContext @ 0x4096700] [verbose] Statistics: 2195400 bytes read, 0 seeks
[8.01.2022, 15:03:15] [CameraUI] Przód: Prebuffer request ended
[8.01.2022, 15:03:15] [CameraUI] Przód: [info] Conversion failed!
[8.01.2022, 15:03:15] [CameraUI] Przód: FFmpeg exited with code: 1 and signal: null (Error)
[8.01.2022, 15:03:15] [CameraUI] Przód: Stream removed from active sessions
[8.01.2022, 15:03:15] [CameraUI] Przód: Currently active streams: 0
[8.01.2022, 15:03:15] [CameraUI] Przód: Stopped video stream.

/usr/local/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js:809
    callback();
    ^
TypeError: callback is not a function
    at Camera.stopStream (/usr/local/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js:809:5)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-camera-ui/src/services/ffmpeg.service.js:81:18)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

**Comment by seydx** [comment]
@grzegorz914 

``[h264_omx @ 0x4095dc0] [warning] /opt/vc/lib/libbcm_host.so not found```

it looks like its not due to camera.ui

https://github.com/raspberrypi/firmware/issues/1366

**Comment by grzegorz914** [comment]
Ok, You are right it’s not a camera.ui problem. 
I close this as solved.

**Comment by macjl** [comment]
Hello,

I have same kind of problem, but not seems to be related to the code for me : 

```
[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: Motion ON
[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: Handling event: Motion switched on
[1/8/2022, 3:40:38 PM] [CameraUI] Received a new VIDEOANALYSIS message {"error":false,"message":"Handled through extern controller"} (Rpicam)
[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: Video fragments requested from HSV
[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: Setting prebuffer stream as input
[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: Prebuffer requested with a duration of -4s
[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: Replacing audio with a dummy track, audio source not found or timed out during probe stream (recording)
[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: Start recording...
[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: Recording command: ffmpeg -hide_banner -analyzeduration 0 -probesize 2085948 -f mp4 -i tcp://127.0.0.1:36693 -f lavfi -i anullsrc=cl=1 -shortest -f mp4 -sn -dn -vcodec libx264 -pix_fmt yuv420p -profile:v baseline -level:v 3.1 -b:v 2000k -force_key_frames expr:eq(t,n_forced*4) -r 30 -vf scale=w=1920:h=1080:force_original_aspect_ratio=1,pad=1920:1080:(ow-iw)/2:(oh-ih)/2 -bsf:a aac_adtstoasc -acodec libfdk_aac -profile:a aac_low -ar 32k -b:a 64k -ac 1 -movflags frag_keyframe+empty_moov+default_base_moof -max_muxing_queue_size 1024 tcp://127.0.0.1:33819
[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'tcp://127.0.0.1:36693':
  Metadata:
    major_brand     : iso5
    minor_version   : 512
    compatible_brands: iso5iso6mp41
    encoder         : Lavf58.45.100
  Duration: 00:04:48.81, start: 287.810838, bitrate: N/A
[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: 
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720, 14 kb/s, 25.01 fps, 25 tbr, 1000k tbn, 2000k tbc (default)
    Metadata:
      handler_name    : VideoHandler

[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: Input #1, lavfi, from 'anullsrc=cl=1':
  Duration: N/A, start: 0.000000, bitrate: 352 kb/s
    Stream #1:0: Audio: pcm_u8, 44100 Hz, 1 channels (FL), u8, 352 kb/s

[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: Recording started
[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #1:0 -> #0:1 (pcm_u8 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help

[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: [mov,mp4,m4a,3gp,3g2,mj2 @ 0xb6faa010] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)

[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: [libx264 @ 0x40ae910] frame MB size (120x68) > level limit (3600)
[libx264 @ 0x40ae910] MB rate (244800) > level limit (108000)

[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: [libx264 @ 0x40ae910] using cpu capabilities: ARMv6 NEON

[1/8/2022, 3:40:38 PM] [CameraUI] Rpicam: [libx264 @ 0x40ae910] profile Constrained Baseline, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x40ae910] 264 - core 160 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=0 ref=2 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=2000 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00

[1/8/2022, 3:40:39 PM] [CameraUI] Rpicam: Output #0, mp4, to 'tcp://127.0.0.1:33819':
  Metadata:
    major_brand     : iso5
    minor_version   : 512
    compatible_brands: iso5iso6mp41
    encoder         : Lavf58.45.100
    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080, q=-1--1, 2000 kb/s, 30 fps, 15360 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.91.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/2000000 buffer size: 0 vbv_delay: N/A
    Stream #0:1: Audio: aac (libfdk_aac) (LC) (mp4a / 0x6134706D), 32000 Hz, mono, s16, 64 kb/s
    Metadata:
      encoder         : Lavc58.91.100 libfdk_aac

[1/8/2022, 3:40:39 PM] [CameraUI] Rpicam: frame=    6 fps=0.0 q=0.0 size=       1kB time=00:00:00.00 bitrate=N/A dup=1 drop=0 speed=   0x    
[1/8/2022, 3:40:39 PM] [CameraUI] Rpicam: frame=   15 fps= 15 q=0.0 size=       1kB time=00:00:00.00 bitrate=N/A dup=2 drop=0 speed=   0x    
[1/8/2022, 3:40:40 PM] [CameraUI] Rpicam: frame=   26 fps= 17 q=0.0 size=       1kB time=00:00:00.00 bitrate=N/A dup=4 drop=0 speed=   0x    
[1/8/2022, 3:40:40 PM] [CameraUI] Rpicam: frame=   37 fps= 18 q=0.0 size=       1kB time=00:00:00.00 bitrate=N/A dup=6 drop=0 speed=   0x    
[1/8/2022, 3:40:41 PM] [CameraUI] Rpicam: frame=   44 fps= 15 q=0.0 size=       1kB time=00:00:00.00 bitrate=N/A dup=7 drop=0 speed=   0x    
[1/8/2022, 3:40:42 PM] [CameraUI] Rpicam: frame=   49 fps= 14 q=44.0 size=       1kB time=00:00:00.09 bitrate= 101.0kbits/s dup=8 drop=0 speed=0.0272x    
[1/8/2022, 3:40:42 PM] [CameraUI] Rpicam: frame=   57 fps= 14 q=36.0 size=       1kB time=00:00:00.35 bitrate=  27.5kbits/s dup=9 drop=0 speed=0.0862x    
[1/8/2022, 3:40:43 PM] [CameraUI] Rpicam: frame=   65 fps= 14 q=31.0 size=       1kB time=00:00:00.57 bitrate=  16.8kbits/s dup=11 drop=0 speed=0.123x    
[1/8/2022, 3:40:44 PM] [CameraUI] Rpicam: frame=   71 fps= 13 q=31.0 size=       1kB time=00:00:00.76 bitrate=  12.6kbits/s dup=12 drop=0 speed=0.146x    
[1/8/2022, 3:40:44 PM] [CameraUI] Rpicam: frame=   78 fps= 13 q=30.0 size=       1kB time=00:00:01.02 bitrate=   9.5kbits/s dup=13 drop=0 speed=0.174x    
[1/8/2022, 3:40:45 PM] [CameraUI] Rpicam: frame=   84 fps= 13 q=30.0 size=       1kB time=00:00:01.24 bitrate=   7.8kbits/s dup=14 drop=0 speed=0.193x    
[1/8/2022, 3:40:45 PM] [CameraUI] Rpicam: frame=   89 fps= 13 q=30.0 size=       1kB time=00:00:01.36 bitrate=   7.1kbits/s dup=15 drop=0 speed=0.194x    
[1/8/2022, 3:40:46 PM] [CameraUI] Rpicam: frame=   95 fps= 13 q=29.0 size=       1kB time=00:00:01.56 bitrate=   6.2kbits/s dup=16 drop=0 speed=0.206x    
[1/8/2022, 3:40:46 PM] [CameraUI] Rpicam: frame=  101 fps= 12 q=29.0 size=       1kB time=00:00:01.79 bitrate=   5.4kbits/s dup=17 drop=0 speed=0.219x    
[1/8/2022, 3:40:47 PM] [CameraUI] Rpicam: Closing recording process
[1/8/2022, 3:40:47 PM] [CameraUI] Resetting motion state because HSV closed recording with reason "3"
[1/8/2022, 3:40:47 PM] [CameraUI] Rpicam: FFMPEG socket closed during read for 8 bytes!
[1/8/2022, 3:40:47 PM] [CameraUI] Rpicam: Skip saving the recording, the file might be corrupted because the recording process was cancelled by HSV
[1/8/2022, 3:40:47 PM] [CameraUI] Rpicam: Prebuffer request ended
[1/8/2022, 3:40:47 PM] [CameraUI] Rpicam: FFmpeg recording process exited (expected)
```

And here is my config : 
```
{
            "name": "CameraUI",
            "debug": true,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": false,
                "localhttp": false
            },
            "smtp": {
                "active": false
            },
            "ftp": {
                "active": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "Rpicam",
                    "motion": true,
                    "motionTimeout": 60,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-f video4linux2 -input_format h264 -framerate 25 -video_size hd720 -i /dev/video0",
                        "debug": true
                    },
                    "videoanalysis": {
                        "active": true
                    }
                }
            ],
            "platform": "CameraUI"
        }
```

**Comment by grzegorz914** [comment]
as @seydx describes in previous post Try to use 
`"vcodec": "copy"`

**Comment by macjl** [comment]
It's far better with the copy codec. I think CPU (rpi4) is not fast enough to encode stream to HSV.

**Comment by seydx** [comment]
> It's far better with the copy codec. I think CPU (rpi4) is not fast enough to encode stream to HSV.

so its working now with "vcodec": "copy" ?

**Comment by macjl** [comment]
Yes it’s working nice!

**Comment by NiccoStar86** [comment]
Hi @seydx, I also experience the issue reported by @grzegorz914 and @macjl about "Skip saving the recording, the file might be corrupted because the recording process was cancelled by HSV". I checked the tips in the previous posts, made some tests, but I can't find a solution.

This is my configuration, installed through Docker on Synology DS918+:
homebridge v1.4.0-beta.4
homebridge-camera-ui v5.0.4
Node.js v16.13.1
npm v8.1.4

Here my config:
```
{
            "name": "CameraUI",
            "port": 8181,
            "debug": true,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": false,
                "localhttp": false
            },
            "smtp": {
                "active": false
            },
            "ftp": {
                "active": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "Ingresso_HSV_2",
                    "excludeSwitch": false,
                    "privacySwitch": false,
                    "motion": true,
                    "motionTimeout": 15,
                    "doorbell": true,
                    "switches": true,
                    "motionDoorbell": false,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://xxx:yyy@192.168.100.250:554/Streaming/Channels/101",
                        "subSource": "-i rtsp://xxx:yyy@192.168.100.250:554/Streaming/Channels/102",
                        "maxStreams": 4,
                        "vcodec": "copy",
                        "stimeout": 10,
                        "audio": false,
                        "debug": true
                    },
                    "videoanalysis": {
                        "active": false
                    }
                }
            ],
            "platform": "CameraUI"
        }
```

and attached the log from camera.ui. [camera.ui.log.txt](https://github.com/seydx/homebridge-camera-ui/files/7849893/camera.ui.log.txt)

Any suggestion is welcome.

Thank you for the great job!

**Comment by seydx** [comment]
@NiccoStar86 

can you post a screenshot from the cameras own settings pls? Like resolution, birste, fps etc

**Comment by NiccoStar86** [comment]
@seydx sure, this is the stream info from VLC:
<img width="828" alt="vlc_stream" src="https://user-images.githubusercontent.com/7814756/149081637-5f41fe57-302a-4991-940c-c7e5a518f6b3.png">

This is the channel configuration from the DVR:
<img width="726" alt="dvr_config" src="https://user-images.githubusercontent.com/7814756/149081656-d6833d0b-c8d4-4679-8809-e9b746538453.png">

The "stream" functionality from the Home app, works very well. If I click on the preview image, refreshed every 10 seconds, the live starts in 1/2 seconds usually!
![IMG_8F2E51022D01-1](https://user-images.githubusercontent.com/7814756/149082025-9fe43264-395a-4b7a-9ac5-98a5c338e7a0.jpeg)

![IMG_54BB17B4A6D0-1](https://user-images.githubusercontent.com/7814756/149082043-15a3e841-7c12-43ae-a87b-27cb1c79cb2a.jpeg)

Let me know if you need other info to investigate this, and I am available to perform the necessary tests!

Thank you

**Comment by seydx** [comment]
> @seydx sure, this is the stream info from VLC: <img alt="vlc_stream" width="828" src="https://user-images.githubusercontent.com/7814756/149081637-5f41fe57-302a-4991-940c-c7e5a518f6b3.png">
> 
> This is the channel configuration from the DVR: <img alt="dvr_config" width="726" src="https://user-images.githubusercontent.com/7814756/149081656-d6833d0b-c8d4-4679-8809-e9b746538453.png">
> 
> The "stream" functionality from the Home app, works very well. If I click on the preview image, refreshed every 10 seconds, the live starts in 1/2 seconds usually! ![IMG_8F2E51022D01-1](https://user-images.githubusercontent.com/7814756/149082025-9fe43264-395a-4b7a-9ac5-98a5c338e7a0.jpeg)
> 
> ![IMG_54BB17B4A6D0-1](https://user-images.githubusercontent.com/7814756/149082043-15a3e841-7c12-43ae-a87b-27cb1c79cb2a.jpeg)
> 
> Let me know if you need other info to investigate this, and I am available to perform the necessary tests!
> 
> Thank you

Can u turn off H264+ pls and can u set frame rate to eg 25? Or 30?

**Comment by NiccoStar86** [comment]
Hi @seydx as you suggested I disabled the H264+ option, and now in H264 "native" the error _Skip saving the recording, the file might be corrupted because the recording process was cancelled by HSV_ disappeared. Many thanks! 👍 

Another strange behavior that I saw, is that HSV events in the bottom bar are visibile only if I trigger the DOORBELL switch and not if I trigger the MOTION switch. I'm probably doing something wrong ... Have you any suggestion? Attached I generated the dedicated logs. [camera.ui.DOORBELL.log.txt](https://github.com/seydx/homebridge-camera-ui/files/7857559/camera.ui.DOORBELL.log.txt) and [camera.ui.MOTION.log.txt](https://github.com/seydx/homebridge-camera-ui/files/7857560/camera.ui.MOTION.log.txt)

Second, the length of the HSV events triggered by the DOORBELL switch is "only" 4 seconds ... is this the HSV standard behavior?

Tell me if you prefer that I open a dedicated issue for these two points.

**Comment by seydx** [comment]
> Hi @seydx as you suggested I disabled the H264+ option, and now in H264 "native" the error _Skip saving the recording, the file might be corrupted because the recording process was cancelled by HSV_ disappeared. Many thanks! 👍
> 
> Another strange behavior that I saw, is that HSV events in the bottom bar are visibile only if I trigger the DOORBELL switch and not if I trigger the MOTION switch. I'm probably doing something wrong ... Have you any suggestion? Attached I generated the dedicated logs. [camera.ui.DOORBELL.log.txt](https://github.com/seydx/homebridge-camera-ui/files/7857559/camera.ui.DOORBELL.log.txt) and [camera.ui.MOTION.log.txt](https://github.com/seydx/homebridge-camera-ui/files/7857560/camera.ui.MOTION.log.txt)
> 
> Second, the length of the HSV events triggered by the DOORBELL switch is "only" 4 seconds ... is this the HSV standard behavior?
> 
> Tell me if you prefer that I open a dedicated issue for these two points.

should be fixed in v5.0.5-beta.8

`sudo npm i -g homebridge-camera-ui@5.0.5-beta.8`

**Comment by NiccoStar86** [comment]
Hi @seydx I installed the 5.0.6 and now the DOORBELL registration in HSV have a duration of 8/9 seconds.

With the latest release I saw that if I trigger the DOORBELL also the MOTION switch is activated. Is this a bug?

The MOTION events are still not visibile in HSV when the MOTION switch are triggered, maybe it's the same point described in the issue #339.

Thank you

**Comment by seydx** [comment]
@NiccoStar86 

v5.0.7-beta.3 is online with better videoanalysis and several bugfixes

`sudo npm i -g homebridge-camera-ui@5.0.7-beta.3`

And yes, its normal that the doorbell also triggers the motion sensor (HKSV needs the motion sensor for recording, and the recording itself is also controlled by the motion sensor)

**Comment by seydx** [comment]
The length of a recording can be controlled through "motionTimeout" within config.json or if you use "videoanalysis" you can set "motionTimeout": 0 to let the camera controll the length of the recording

**Comment by NiccoStar86** [comment]
Perfect @seydx thank you!
