### ISSUE TITLE
Dummy switches don't showup

### ISSUE THREAD

**Issue by danch99** [SeydX/homebridge-camera-ui#50]
Hi,

I'm running homebridge on a MacOs machine.
I've connected an rtsp wyse camera and a raspberry http camera streaming mjpeg.

I'm not able to see the dummy switches in the homekit app.

Here is my config.json file:
```
        {
            "name": "CameraUI",
            "port": 8591,
            "auth": "none",
            "language": "en",
            "debug": true,
            "reset": true,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": false,
                "localhttp": false
            },
            "ssl": {
                "active": false
            },
            "options": {
                "videoProcessor": "/usr/local/lib/node_modules/homebridge-nest-cam/node_modules/ffmpeg-for-homebridge/ffmpeg",
                "ffmpegExecPath": "/usr/local/lib/node_modules/homebridge-nest-cam/node_modules/ffmpeg-for-homebridge/ffmpeg"
            },
            "cameras": [
                {
                    "name": "GarageCam",
                    "manufacturer": "Wyze",
                    "motion": true,
                    "doorbell": true,
                    "switches": true,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://xxxxx:xxxxx@xxx.xxx.x.xx/live",
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0,
                        "vcodec": "copy",
                        "audio": true,
                        "debug": true,
                        "socketPort": 8100
                    }
                },
                {
                    "name": "PiZeroCam",
                    "manufacturer": "Raspberry",
                    "model": "PiZero",
                    "motion": true,
                    "doorbell": true,
                    "switches": true,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i http://xxx.xxx.x.xx:xxxx/",
                        "maxWidth": 1024,
                        "maxHeight": 768,
                        "maxFPS": 15,
                        "vcodec": "copy",
                        "debug": true,
                        "socketPort": 8101
                    }
                }
            ],
            "platform": "CameraUI"
        }
```

Thanks

**Comment by SeydX** [comment]
@danch99 

"ffmpegExecPath" is not used anymore, u can remove it.

Cause of not appearing switches, can deactivate switches, restart homebridge, activate switches again restart homebridge and post the log from the last restart here pls

**Comment by danch99** [comment]
I tryied to remove ffmpegExecPath as you suggest and then it does’t work anymore. I can’t even get the snapshot.

About the switches, here is the log after I re-enable and restart:

[10/20/2020, 9:47:08 PM] [HB Supervisor] Restarting Homebridge...
[10/20/2020, 9:47:08 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[10/20/2020, 9:47:08 PM] [HB Supervisor] Started Homebridge v1.2.3 with PID: 22298
[10/20/2020, 9:47:09 PM] Loaded config.json with 0 accessories and 7 platforms.
[10/20/2020, 9:47:09 PM] ---
[10/20/2020, 9:47:09 PM] Loaded plugin: homebridge-camera-ui@3.0.9
[10/20/2020, 9:47:10 PM] Registering platform 'homebridge-camera-ui.CameraUI'
[10/20/2020, 9:47:10 PM] ---
[10/20/2020, 9:47:10 PM] Loaded plugin: homebridge-config-ui-x@4.29.0
[10/20/2020, 9:47:10 PM] Registering platform 'homebridge-config-ui-x.config'
[10/20/2020, 9:47:10 PM] ---
[10/20/2020, 9:47:10 PM] Loaded plugin: homebridge-nest@4.4.12
[10/20/2020, 9:47:10 PM] Registering platform 'homebridge-nest.Nest'
[10/20/2020, 9:47:10 PM] ---
[10/20/2020, 9:47:10 PM] Loaded plugin: homebridge-nest-cam@5.4.2
[10/20/2020, 9:47:10 PM] Registering platform 'homebridge-nest-cam.Nest-cam'
[10/20/2020, 9:47:10 PM] ---
[10/20/2020, 9:47:10 PM] Loaded plugin: homebridge-smartthings@2.3.8
[10/20/2020, 9:47:10 PM] Registering platform 'homebridge-smartthings.SmartThings-v2'
[10/20/2020, 9:47:10 PM] ---
[10/20/2020, 9:47:10 PM] Loaded plugin: homebridge-weather-plus@3.2.2
[10/20/2020, 9:47:11 PM] Registering platform 'homebridge-weather-plus.WeatherPlus'
[10/20/2020, 9:47:11 PM] ---
[10/20/2020, 9:47:11 PM] Loaded plugin: @milo526/homebridge-tuya-web@0.4.8
[10/20/2020, 9:47:11 PM] Registering platform '@milo526/homebridge-tuya-web.TuyaWebPlatform'
[10/20/2020, 9:47:11 PM] ---
[10/20/2020, 9:47:11 PM] Loading 7 platforms...
[10/20/2020, 9:47:11 PM] [Nest] Initializing Nest platform...
[10/20/2020, 9:47:11 PM] [Config] Initializing config platform...
[10/20/2020, 9:47:11 PM] [Config] Running in Service Mode
[10/20/2020, 9:47:11 PM] [Nest-cam] Initializing Nest-cam platform...
[10/20/2020, 9:47:11 PM] [SmartThings-v2] Initializing SmartThings-v2 platform...
INFO: Homebridge Version: 2.6
INFO: SmartThings-v2 Plugin Version: 2.3.8
INFO: Checking Package Version for Updates...
[10/20/2020, 9:47:11 PM] [WeatherPlus] Initializing WeatherPlus platform...
[10/20/2020, 9:47:11 PM] [WeatherPlus] Adding station with weather service OpenWeatherMap named 'Virtual Weather'
[10/20/2020, 9:47:11 PM] Initializing platform accessory 'Virtual Weather'...
[10/20/2020, 9:47:11 PM] Initializing platform accessory 'Today'...
[10/20/2020, 9:47:11 PM] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
[10/20/2020, 9:47:11 PM] [CameraUI] Initializing CameraUI platform...
[10/20/2020, 9:47:11 PM] [Nest-cam] Configuring accessory Front Door
[10/20/2020, 9:47:11 PM] [TuyaWebPlatform] Loading accessory from cache: Switch 1
[10/20/2020, 9:47:11 PM] [TuyaWebPlatform] Loading accessory from cache: Switch 2
[10/20/2020, 9:47:11 PM] [Nest] Fetching Nest devices.
INFO: Fetching SmartThings-v2 Devices. NOTICE: This may take a moment if you have a large number of device data is being loaded!
GOOD: Refreshing All Device Data | Source: (First Launch)
[10/20/2020, 9:47:11 PM] [CameraUI] GarageCam: Configuring unbridged accessory...
[10/20/2020, 9:47:11 PM] [CameraUI] PiZeroCam: Configuring unbridged accessory...
[10/20/2020, 9:47:11 PM] [CameraUI] GarageCam: Removing bridged accessory...
[10/20/2020, 9:47:11 PM] GarageCam 662D is running on port 52100.
[10/20/2020, 9:47:11 PM] Please add [GarageCam 662D] manually in Home app. Setup Code: 301-31-047
[10/20/2020, 9:47:11 PM] PiZeroCam 394A is running on port 52101.
[10/20/2020, 9:47:11 PM] Please add [PiZeroCam 394A] manually in Home app. Setup Code: 301-31-047
[10/20/2020, 9:47:11 PM] [CameraUI] Multiple network interfaces detected ("en0", "en6", "en1", "awdl0", "llw0", "utun0", "utun1", "utun2", "utun3"). If you encounter issues with streaming video you may need to set interfaceName. If not set, "en0" will be used.
Setup Payload:
X-HM://0023YVDD324J9
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:

 ┌────────────┐
 │ 301-31-047 │
 └────────────┘

[10/20/2020, 9:47:11 PM] Homebridge v1.2.3 is running on port 51826.
(node:22298) UnhandledPromiseRejectionWarning: Error: Cannot find the bridged Accessory to remove.
 at Bridge.Accessory._this.removeBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:475:13)
 at Bridge.Accessory._this.removeBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:487:12)
 at Server.handleUnregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:554:17)
 at HomebridgeAPI.emit (events.js:314:20)
 at HomebridgeAPI.unregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:331:10)
 at CameraUI.removeAccessory (/usr/local/lib/node_modules/homebridge-camera-ui/src/platform.js:326:14)
 at /usr/local/lib/node_modules/homebridge-camera-ui/src/platform.js:211:14
 at Array.forEach (<anonymous>)
 at CameraUI.didFinishLaunching (/usr/local/lib/node_modules/homebridge-camera-ui/src/platform.js:206:22)
 at HomebridgeAPI.emit (events.js:326:22)
(node:22298) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22298) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
INFO: INFO: Your plugin version is up-to-date
NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.8
[10/20/2020, 9:47:12 PM] [TuyaWebPlatform] Existing Accessory found [Name: Switch 1] [Tuya ID: 240057632cf432d5acdf_1] [HomeBridge ID: 90da8b48-9711-4669-9ada-af5ef5a24a2e]
[10/20/2020, 9:47:12 PM] [TuyaWebPlatform] [Switch 1] Characteristic.On - Enabled
[10/20/2020, 9:47:12 PM] [TuyaWebPlatform] Existing Accessory found [Name: Switch 2] [Tuya ID: 240057632cf432d5acdf_2] [HomeBridge ID: 90d99061-64f8-43da-9f76-ce1db760e9f7]
[10/20/2020, 9:47:12 PM] [TuyaWebPlatform] [Switch 2] Characteristic.On - Enabled
NOTICE: Temperature Unit is Now: (C)
NOTICE: Updating Global Values | HubIP: 192.168.1.110 | UseLocal: false
WARN: Devices to Remove: (0) []
INFO: Devices to Update: (29)
GOOD: Devices to Create: (0) []
ALERT: Total Initialization Time: (3 seconds)
NOTICE: Unknown Capabilities: ["Holdable Button","Three Axis","Occupancy Sensor"]
INFO: SmartThings DeviceCache Size: (29)
INFO: WebServer Initiated...
INFO: Sending StartDirect Request to SmartThings | SendToLocalHub: (false)
INFO: Direct Connect Active | Listening at 192.168.1.20:8000
INFO: SmartThings-v2 Hub Communication Established
[10/20/2020, 9:47:15 PM] [Nest] initing thermostat "Entryway Thermostat": deviceId: 09AE01AC41180B4J structureId: 04a34670-203b-11ea-80c7-128dc41c8173
[10/20/2020, 9:47:15 PM] [Nest] initing home_away_sensor "Home Occupied": deviceId: 04a34670-203b-11ea-80c7-128dc41c8173 structureId: 04a34670-203b-11ea-80c7-128dc41c8173



-------------------------
Dan Charbit
-------------------------

**Comment by SeydX** [comment]
@danch99 

can u remove ``"unbridge": true,`` from all cameras and try again pls

dont forget to post your log after restart

**Comment by danch99** [comment]
I already tried, in fact I tried unbridge with the hope it will solve the problem.
But just in case, here is a new attempt bridged:

[10/20/2020, 10:02:44 PM] [HB Supervisor] Restarting Homebridge...
[10/20/2020, 10:02:44 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[10/20/2020, 10:02:44 PM] [HB Supervisor] Started Homebridge v1.2.3 with PID: 23122
[10/20/2020, 10:02:45 PM] Loaded config.json with 0 accessories and 7 platforms.
[10/20/2020, 10:02:45 PM] ---
[10/20/2020, 10:02:45 PM] Loaded plugin: homebridge-camera-ui@3.0.9
[10/20/2020, 10:02:45 PM] Registering platform 'homebridge-camera-ui.CameraUI'
[10/20/2020, 10:02:45 PM] ---
[10/20/2020, 10:02:45 PM] Loaded plugin: homebridge-config-ui-x@4.29.0
[10/20/2020, 10:02:45 PM] Registering platform 'homebridge-config-ui-x.config'
[10/20/2020, 10:02:45 PM] ---
[10/20/2020, 10:02:46 PM] Loaded plugin: homebridge-nest@4.4.12
[10/20/2020, 10:02:46 PM] Registering platform 'homebridge-nest.Nest'
[10/20/2020, 10:02:46 PM] ---
[10/20/2020, 10:02:46 PM] Loaded plugin: homebridge-nest-cam@5.4.2
[10/20/2020, 10:02:46 PM] Registering platform 'homebridge-nest-cam.Nest-cam'
[10/20/2020, 10:02:46 PM] ---
[10/20/2020, 10:02:46 PM] Loaded plugin: homebridge-smartthings@2.3.8
[10/20/2020, 10:02:46 PM] Registering platform 'homebridge-smartthings.SmartThings-v2'
[10/20/2020, 10:02:46 PM] ---
[10/20/2020, 10:02:46 PM] Loaded plugin: homebridge-weather-plus@3.2.2
[10/20/2020, 10:02:46 PM] Registering platform 'homebridge-weather-plus.WeatherPlus'
[10/20/2020, 10:02:46 PM] ---
[10/20/2020, 10:02:46 PM] Loaded plugin: @milo526/homebridge-tuya-web@0.4.8
[10/20/2020, 10:02:46 PM] Registering platform '@milo526/homebridge-tuya-web.TuyaWebPlatform'
[10/20/2020, 10:02:46 PM] ---
[10/20/2020, 10:02:46 PM] Loading 7 platforms...
[10/20/2020, 10:02:46 PM] [Nest] Initializing Nest platform...
[10/20/2020, 10:02:46 PM] [Config] Initializing config platform...
[10/20/2020, 10:02:46 PM] [Config] Running in Service Mode
[10/20/2020, 10:02:46 PM] [Nest-cam] Initializing Nest-cam platform...
[10/20/2020, 10:02:46 PM] [SmartThings-v2] Initializing SmartThings-v2 platform...
INFO: Homebridge Version: 2.6
INFO: SmartThings-v2 Plugin Version: 2.3.8
INFO: Checking Package Version for Updates...
[10/20/2020, 10:02:47 PM] [WeatherPlus] Initializing WeatherPlus platform...
[10/20/2020, 10:02:47 PM] [WeatherPlus] Adding station with weather service OpenWeatherMap named 'Virtual Weather'
[10/20/2020, 10:02:47 PM] Initializing platform accessory 'Virtual Weather'...
[10/20/2020, 10:02:47 PM] Initializing platform accessory 'Today'...
[10/20/2020, 10:02:47 PM] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
[10/20/2020, 10:02:47 PM] [CameraUI] Initializing CameraUI platform...
[10/20/2020, 10:02:47 PM] [Nest-cam] Configuring accessory Front Door
[10/20/2020, 10:02:47 PM] [TuyaWebPlatform] Loading accessory from cache: Switch 1
[10/20/2020, 10:02:47 PM] [TuyaWebPlatform] Loading accessory from cache: Switch 2
[10/20/2020, 10:02:47 PM] [Nest] Fetching Nest devices.
INFO: Fetching SmartThings-v2 Devices. NOTICE: This may take a moment if you have a large number of device data is being loaded!
GOOD: Refreshing All Device Data | Source: (First Launch)
[10/20/2020, 10:02:47 PM] [CameraUI] GarageCam: Configuring bridged accessory...
[10/20/2020, 10:02:47 PM] [CameraUI] PiZeroCam: Configuring bridged accessory...
[10/20/2020, 10:02:47 PM] [CameraUI] Configuring User Interface
[10/20/2020, 10:02:47 PM] [CameraUI] Multiple network interfaces detected ("en0", "en6", "en1", "awdl0", "llw0", "utun0", "utun1", "utun2", "utun3"). If you encounter issues with streaming video you may need to set interfaceName. If not set, "en0" will be used.
Setup Payload:
X-HM://0023YVDD324J9
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:

 ┌────────────┐
 │ 301-31-047 │
 └────────────┘

[10/20/2020, 10:02:47 PM] Homebridge v1.2.3 is running on port 51826.
[10/20/2020, 10:02:47 PM] [CameraUI] Starting User Interface
[10/20/2020, 10:02:47 PM] [CameraUI] CameraUI is listening on port 8591
INFO: INFO: Your plugin version is up-to-date
NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.8
[10/20/2020, 10:02:48 PM] [TuyaWebPlatform] Existing Accessory found [Name: Switch 1] [Tuya ID: 240057632cf432d5acdf_1] [HomeBridge ID: 90da8b48-9711-4669-9ada-af5ef5a24a2e]
[10/20/2020, 10:02:48 PM] [TuyaWebPlatform] [Switch 1] Characteristic.On - Enabled
[10/20/2020, 10:02:48 PM] [TuyaWebPlatform] Existing Accessory found [Name: Switch 2] [Tuya ID: 240057632cf432d5acdf_2] [HomeBridge ID: 90d99061-64f8-43da-9f76-ce1db760e9f7]
[10/20/2020, 10:02:48 PM] [TuyaWebPlatform] [Switch 2] Characteristic.On - Enabled
NOTICE: Temperature Unit is Now: (C)
NOTICE: Updating Global Values | HubIP: 192.168.1.110 | UseLocal: false
WARN: Devices to Remove: (0) []
INFO: Devices to Update: (29)
GOOD: Devices to Create: (0) []
ALERT: Total Initialization Time: (2 seconds)
NOTICE: Unknown Capabilities: ["Holdable Button","Three Axis","Occupancy Sensor"]
INFO: SmartThings DeviceCache Size: (29)
INFO: WebServer Initiated...
INFO: Sending StartDirect Request to SmartThings | SendToLocalHub: (false)
INFO: Direct Connect Active | Listening at 192.168.1.20:8000
INFO: SmartThings-v2 Hub Communication Established
[10/20/2020, 10:02:50 PM] [Nest] initing thermostat "Entryway Thermostat": deviceId: 09AE01AC41180B4J structureId: 04a34670-203b-11ea-80c7-128dc41c8173
[10/20/2020, 10:02:50 PM] [Nest] initing home_away_sensor "Home Occupied": deviceId: 04a34670-203b-11ea-80c7-128dc41c8173 structureId: 04a34670-203b-11ea-80c7-128dc41c8173
[10/20/2020, 10:03:37 PM] [TuyaWebPlatform] [Switch 2] - Requesting device state
[10/20/2020, 10:03:37 PM] [TuyaWebPlatform] [Switch 2] - Creating new debounced promise
[10/20/2020, 10:03:37 PM] [TuyaWebPlatform] [Switch 2] - Triggering debouncedDeviceStateRequest
[10/20/2020, 10:03:37 PM] [TuyaWebPlatform] [Switch 1] - Requesting device state
[10/20/2020, 10:03:37 PM] [TuyaWebPlatform] [Switch 1] - Creating new debounced promise
[10/20/2020, 10:03:37 PM] [TuyaWebPlatform] [Switch 1] - Triggering debouncedDeviceStateRequest
[10/20/2020, 10:03:37 PM] [TuyaWebPlatform] [Switch 2] - Unsetting debouncedDeviceStateRequestPromise
[10/20/2020, 10:03:37 PM] [TuyaWebPlatform] [Switch 2] - Resolving resolveDeviceStateRequest from cache
[10/20/2020, 10:03:37 PM] [TuyaWebPlatform] [Switch 2] Characteristic.On - [GET] false
[10/20/2020, 10:03:37 PM] [TuyaWebPlatform] [Switch 1] - Unsetting debouncedDeviceStateRequestPromise
[10/20/2020, 10:03:37 PM] [TuyaWebPlatform] [Switch 1] - Resolving resolveDeviceStateRequest from cache
[10/20/2020, 10:03:37 PM] [TuyaWebPlatform] [Switch 1] Characteristic.On - [GET] false
[10/20/2020, 10:03:42 PM] [CameraUI] PiZeroCam: Snapshot requested: 1280 x 720
[10/20/2020, 10:03:42 PM] [CameraUI] PiZeroCam: Sending snapshot: 1280 x 720
[10/20/2020, 10:03:42 PM] [CameraUI] GarageCam: Snapshot requested: 1280 x 720
[10/20/2020, 10:03:42 PM] [CameraUI] GarageCam: Sending snapshot: 1280 x 720
[10/20/2020, 10:03:50 PM] [CameraUI] GarageCam: Starting video stream: native x native, native fps, ??? kbps
[10/20/2020, 10:03:57 PM] [CameraUI] GarageCam: Stopped video stream.
[10/20/2020, 10:04:07 PM] [CameraUI] GarageCam: Starting video stream: native x native, native fps, ??? kbps
[10/20/2020, 10:04:08 PM] [CameraUI] GarageCam: Stopped video stream.

-------------------------
Dan Charbit
-------------------------

**Comment by SeydX** [comment]
Hey could you try removing all cameras and restarting homebridge

update to v3.1.0 and add the cameras again width ``"unbridge": true``

restart homebridge and post log pls

**Comment by jeylites** [comment]
I have a similar problem, no dummy switch. Motion shows up on Homekit but it doesn't trigger when there's activity. Stream and Snapshot works


**Logs**
```
[10/21/2020, 6:41:44 PM] [Camera-FFmpeg] [SIDE] Configuring cached bridged accessory...
[10/21/2020, 6:41:44 PM] [Camera-FFmpeg] [MAINSTREET] Configuring cached bridged accessory...
[10/21/2020, 6:41:44 PM] [CameraUI] [Plugin] HALL-UI: Configuring cached bridged accessory...
[10/21/2020, 6:41:44 PM] [Camera-FFmpeg] Setting up MQTT connection with topic homebridge...
[10/21/2020, 6:41:44 PM] [CameraUI] [Interface] Configuring User Interface
(node:21018) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 shutdown listeners added to [HomebridgeAPI]. Use emitter.setMaxListeners() to increase limit
Setup Payload:

[10/21/2020, 6:41:44 PM] Homebridge v1.2.3 is running on port 51566.
[10/21/2020, 6:41:44 PM] [Camera-FFmpeg] MQTT connected.
[10/21/2020, 6:41:44 PM] [CameraUI] [Interface] Starting User Interface
[10/21/2020, 6:41:45 PM] [CameraUI] [Interface] CameraUI is listening on port 3333
```

**Config**

```
  ],
            "platform": "Camera-ffmpeg"
        },
        {
            "name": "CameraUI",
            "port": 3333,
            "auth": "form",
            "language": "en",
            "debug": true,
            "reset": false,
            "mqtt": {
                "active": true,
                "host": "192.168.1.200",
                "port": 1883,
                "topic": "camotion",
                "on_message": "ON"
            },
            "http": {
                "active": false,
                "localhttp": false
            },
            "ssl": {
                "active": false
            },
            "options": {
                "videoProcessor": "ffmpeg",
                "interfaceName": "eth0"
            },
            "cameras": [
                {
                    "name": "HALL-UI",
                    "motion": true,
                    "switches": true,
                    "motionTimeout": 5,
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-i rtsp://adminXXXX:4509/6",
                        "stillImageSource": "-i rtsp://adminXXXX:4509/6",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "maxBitrate": 299,
                        "vcodec": "libx264",
                        "packetSize": 1316
                    }
                }
            ],
            "platform": "CameraUI"
        }
    ],
    "accessories": []
}
```

**Comment by SeydX** [comment]
I found the problem

Its because the plugin needs a second parameter to expose the switches.

The second param is mqtt or http needs to be active. This should be fixed in the neyt version

**Comment by SeydX** [comment]
v3.1.1 ist online now and should fix this issue

Can you confirm pls

**Comment by danch99** [comment]
YES now it works !! I can see them !
Not sure how to use them though 😄 

Thanks

**Comment by SeydX** [comment]
Allright

Hehe, you can create automations based on this switches, just play with them

Have fun 👍🏼

**Comment by jeylites** [comment]
I see the motion and the dummy switches but still can't figure out why motion is not triggered when there's an activity? I walked as close as I can to the camera in a well-lited area. Still, nothing but it did trigger the camera's internal motion function.

**Comment by danch99** [comment]
Same thing for me.
I even get the notification from wyze cam app, but nothing in HomeKit.



-------------------------
Dan Charbit
-------------------------

**Comment by SeydX** [comment]
@jeylites 

The plugin has not a own native movement detection. It is based on the cameras movement detection. The Plugin offers several ways to use the movement detection from the camera. Like MQTT, FTP, HTTP etc.

For example, if your camera uploads a file on movement detection, u can use https://github.com/Sunoo/homebridge-ftp-motion etc

**Comment by danch99** [comment]
Is there a documentation somewhere ?



-------------------------
Dan Charbit
-------------------------

**Comment by SeydX** [comment]
Im currently working on the wiki page

**Comment by danch99** [comment]
awesome !
Can't wait to read it.

**Comment by jeylites** [comment]
@SeydX 
That makes sense why we couldn't get it working. looking forward to that wiki page :)

**Comment by SeydX** [comment]
@danch99 @jeylites 

the automation wiki is now updated

https://github.com/SeydX/homebridge-camera-ui/wiki/Automation

**Comment by jeylites** [comment]
@SeydX 

but I still don't understand how to get it working. Basically, what I'm trying to achieve is to trigger lights on motion. I see the motion alert and switch populated in HK.
